/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.brand.category.map.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.marketplace.brand.category.map.model.BrandCategoryMap;
import com.marketplace.brand.category.map.model.BrandCategoryMapModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BrandCategoryMap service. Represents a row in the &quot;marketplace_brandcategorymap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BrandCategoryMapModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BrandCategoryMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BrandCategoryMapImpl
 * @generated
 */
public class BrandCategoryMapModelImpl
	extends BaseModelImpl<BrandCategoryMap> implements BrandCategoryMapModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a brand category map model instance should use the <code>BrandCategoryMap</code> interface instead.
	 */
	public static final String TABLE_NAME = "marketplace_brandcategorymap";

	public static final Object[][] TABLE_COLUMNS = {
		{"brandCategoryMapId", Types.BIGINT}, {"brandId", Types.BIGINT},
		{"categoryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("brandCategoryMapId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("brandId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table marketplace_brandcategorymap (brandCategoryMapId LONG not null primary key,brandId LONG,categoryId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table marketplace_brandcategorymap";

	public static final String ORDER_BY_JPQL =
		" ORDER BY brandCategoryMap.brandCategoryMapId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY marketplace_brandcategorymap.brandCategoryMapId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BRANDID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BRANDCATEGORYMAPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BrandCategoryMapModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _brandCategoryMapId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBrandCategoryMapId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _brandCategoryMapId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BrandCategoryMap.class;
	}

	@Override
	public String getModelClassName() {
		return BrandCategoryMap.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BrandCategoryMap, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BrandCategoryMap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BrandCategoryMap, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BrandCategoryMap)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BrandCategoryMap, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BrandCategoryMap, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BrandCategoryMap)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BrandCategoryMap, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BrandCategoryMap, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<BrandCategoryMap, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<BrandCategoryMap, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<BrandCategoryMap, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<BrandCategoryMap, Object>>();
		Map<String, BiConsumer<BrandCategoryMap, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<BrandCategoryMap, ?>>();

		attributeGetterFunctions.put(
			"brandCategoryMapId", BrandCategoryMap::getBrandCategoryMapId);
		attributeSetterBiConsumers.put(
			"brandCategoryMapId",
			(BiConsumer<BrandCategoryMap, Long>)
				BrandCategoryMap::setBrandCategoryMapId);
		attributeGetterFunctions.put("brandId", BrandCategoryMap::getBrandId);
		attributeSetterBiConsumers.put(
			"brandId",
			(BiConsumer<BrandCategoryMap, Long>)BrandCategoryMap::setBrandId);
		attributeGetterFunctions.put(
			"categoryId", BrandCategoryMap::getCategoryId);
		attributeSetterBiConsumers.put(
			"categoryId",
			(BiConsumer<BrandCategoryMap, Long>)
				BrandCategoryMap::setCategoryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getBrandCategoryMapId() {
		return _brandCategoryMapId;
	}

	@Override
	public void setBrandCategoryMapId(long brandCategoryMapId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_brandCategoryMapId = brandCategoryMapId;
	}

	@Override
	public long getBrandId() {
		return _brandId;
	}

	@Override
	public void setBrandId(long brandId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_brandId = brandId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBrandId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("brandId"));
	}

	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryId = categoryId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, BrandCategoryMap.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BrandCategoryMap toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BrandCategoryMap>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BrandCategoryMapImpl brandCategoryMapImpl = new BrandCategoryMapImpl();

		brandCategoryMapImpl.setBrandCategoryMapId(getBrandCategoryMapId());
		brandCategoryMapImpl.setBrandId(getBrandId());
		brandCategoryMapImpl.setCategoryId(getCategoryId());

		brandCategoryMapImpl.resetOriginalValues();

		return brandCategoryMapImpl;
	}

	@Override
	public BrandCategoryMap cloneWithOriginalValues() {
		BrandCategoryMapImpl brandCategoryMapImpl = new BrandCategoryMapImpl();

		brandCategoryMapImpl.setBrandCategoryMapId(
			this.<Long>getColumnOriginalValue("brandCategoryMapId"));
		brandCategoryMapImpl.setBrandId(
			this.<Long>getColumnOriginalValue("brandId"));
		brandCategoryMapImpl.setCategoryId(
			this.<Long>getColumnOriginalValue("categoryId"));

		return brandCategoryMapImpl;
	}

	@Override
	public int compareTo(BrandCategoryMap brandCategoryMap) {
		long primaryKey = brandCategoryMap.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BrandCategoryMap)) {
			return false;
		}

		BrandCategoryMap brandCategoryMap = (BrandCategoryMap)object;

		long primaryKey = brandCategoryMap.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BrandCategoryMap> toCacheModel() {
		BrandCategoryMapCacheModel brandCategoryMapCacheModel =
			new BrandCategoryMapCacheModel();

		brandCategoryMapCacheModel.brandCategoryMapId = getBrandCategoryMapId();

		brandCategoryMapCacheModel.brandId = getBrandId();

		brandCategoryMapCacheModel.categoryId = getCategoryId();

		return brandCategoryMapCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BrandCategoryMap, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BrandCategoryMap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BrandCategoryMap, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(BrandCategoryMap)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BrandCategoryMap>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BrandCategoryMap.class, ModelWrapper.class);

	}

	private long _brandCategoryMapId;
	private long _brandId;
	private long _categoryId;

	public <T> T getColumnValue(String columnName) {
		Function<BrandCategoryMap, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BrandCategoryMap)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("brandCategoryMapId", _brandCategoryMapId);
		_columnOriginalValues.put("brandId", _brandId);
		_columnOriginalValues.put("categoryId", _categoryId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("brandCategoryMapId", 1L);

		columnBitmasks.put("brandId", 2L);

		columnBitmasks.put("categoryId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BrandCategoryMap _escapedModel;

}