/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.product.spec.value.map.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.marketplace.product.spec.value.map.model.ProductSpecValueMap;
import com.marketplace.product.spec.value.map.model.ProductSpecValueMapModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProductSpecValueMap service. Represents a row in the &quot;marketplace_product_spec_value&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProductSpecValueMapModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductSpecValueMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductSpecValueMapImpl
 * @generated
 */
public class ProductSpecValueMapModelImpl
	extends BaseModelImpl<ProductSpecValueMap>
	implements ProductSpecValueMapModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product spec value map model instance should use the <code>ProductSpecValueMap</code> interface instead.
	 */
	public static final String TABLE_NAME = "marketplace_product_spec_value";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"productSpecValueId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"productSpecificationId", Types.BIGINT},
		{"specificationValueLabelId", Types.BIGINT},
		{"specificationValueLabel", Types.VARCHAR},
		{"specificationValueUOM", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"ipAddress", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productSpecValueId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productSpecificationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("specificationValueLabelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("specificationValueLabel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("specificationValueUOM", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table marketplace_product_spec_value (uuid_ VARCHAR(75) null,productSpecValueId LONG not null primary key,groupId LONG,productSpecificationId LONG,specificationValueLabelId LONG,specificationValueLabel VARCHAR(75) null,specificationValueUOM VARCHAR(75) null,companyId LONG,userId LONG,userName VARCHAR(75) null,createdBy LONG,modifiedBy LONG,createDate DATE null,modifiedDate DATE null,ipAddress VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table marketplace_product_spec_value";

	public static final String ORDER_BY_JPQL =
		" ORDER BY productSpecValueMap.productSpecValueId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY marketplace_product_spec_value.productSpecValueId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRODUCTSPECIFICATIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SPECIFICATIONVALUELABELID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRODUCTSPECVALUEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProductSpecValueMapModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _productSpecValueId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProductSpecValueId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _productSpecValueId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProductSpecValueMap.class;
	}

	@Override
	public String getModelClassName() {
		return ProductSpecValueMap.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProductSpecValueMap, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProductSpecValueMap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductSpecValueMap, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProductSpecValueMap)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProductSpecValueMap, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProductSpecValueMap, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProductSpecValueMap)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProductSpecValueMap, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProductSpecValueMap, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ProductSpecValueMap, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProductSpecValueMap, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProductSpecValueMap, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProductSpecValueMap, Object>>();
		Map<String, BiConsumer<ProductSpecValueMap, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ProductSpecValueMap, ?>>();

		attributeGetterFunctions.put("uuid", ProductSpecValueMap::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProductSpecValueMap, String>)
				ProductSpecValueMap::setUuid);
		attributeGetterFunctions.put(
			"productSpecValueId", ProductSpecValueMap::getProductSpecValueId);
		attributeSetterBiConsumers.put(
			"productSpecValueId",
			(BiConsumer<ProductSpecValueMap, Long>)
				ProductSpecValueMap::setProductSpecValueId);
		attributeGetterFunctions.put(
			"groupId", ProductSpecValueMap::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProductSpecValueMap, Long>)
				ProductSpecValueMap::setGroupId);
		attributeGetterFunctions.put(
			"productSpecificationId",
			ProductSpecValueMap::getProductSpecificationId);
		attributeSetterBiConsumers.put(
			"productSpecificationId",
			(BiConsumer<ProductSpecValueMap, Long>)
				ProductSpecValueMap::setProductSpecificationId);
		attributeGetterFunctions.put(
			"specificationValueLabelId",
			ProductSpecValueMap::getSpecificationValueLabelId);
		attributeSetterBiConsumers.put(
			"specificationValueLabelId",
			(BiConsumer<ProductSpecValueMap, Long>)
				ProductSpecValueMap::setSpecificationValueLabelId);
		attributeGetterFunctions.put(
			"specificationValueLabel",
			ProductSpecValueMap::getSpecificationValueLabel);
		attributeSetterBiConsumers.put(
			"specificationValueLabel",
			(BiConsumer<ProductSpecValueMap, String>)
				ProductSpecValueMap::setSpecificationValueLabel);
		attributeGetterFunctions.put(
			"specificationValueUOM",
			ProductSpecValueMap::getSpecificationValueUOM);
		attributeSetterBiConsumers.put(
			"specificationValueUOM",
			(BiConsumer<ProductSpecValueMap, String>)
				ProductSpecValueMap::setSpecificationValueUOM);
		attributeGetterFunctions.put(
			"companyId", ProductSpecValueMap::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProductSpecValueMap, Long>)
				ProductSpecValueMap::setCompanyId);
		attributeGetterFunctions.put("userId", ProductSpecValueMap::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ProductSpecValueMap, Long>)
				ProductSpecValueMap::setUserId);
		attributeGetterFunctions.put(
			"userName", ProductSpecValueMap::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ProductSpecValueMap, String>)
				ProductSpecValueMap::setUserName);
		attributeGetterFunctions.put(
			"createdBy", ProductSpecValueMap::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ProductSpecValueMap, Long>)
				ProductSpecValueMap::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", ProductSpecValueMap::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ProductSpecValueMap, Long>)
				ProductSpecValueMap::setModifiedBy);
		attributeGetterFunctions.put(
			"createDate", ProductSpecValueMap::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProductSpecValueMap, Date>)
				ProductSpecValueMap::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ProductSpecValueMap::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProductSpecValueMap, Date>)
				ProductSpecValueMap::setModifiedDate);
		attributeGetterFunctions.put(
			"ipAddress", ProductSpecValueMap::getIpAddress);
		attributeSetterBiConsumers.put(
			"ipAddress",
			(BiConsumer<ProductSpecValueMap, String>)
				ProductSpecValueMap::setIpAddress);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getProductSpecValueId() {
		return _productSpecValueId;
	}

	@Override
	public void setProductSpecValueId(long productSpecValueId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productSpecValueId = productSpecValueId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getProductSpecificationId() {
		return _productSpecificationId;
	}

	@Override
	public void setProductSpecificationId(long productSpecificationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productSpecificationId = productSpecificationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProductSpecificationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("productSpecificationId"));
	}

	@Override
	public long getSpecificationValueLabelId() {
		return _specificationValueLabelId;
	}

	@Override
	public void setSpecificationValueLabelId(long specificationValueLabelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specificationValueLabelId = specificationValueLabelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSpecificationValueLabelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("specificationValueLabelId"));
	}

	@Override
	public String getSpecificationValueLabel() {
		if (_specificationValueLabel == null) {
			return "";
		}
		else {
			return _specificationValueLabel;
		}
	}

	@Override
	public void setSpecificationValueLabel(String specificationValueLabel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specificationValueLabel = specificationValueLabel;
	}

	@Override
	public String getSpecificationValueUOM() {
		if (_specificationValueUOM == null) {
			return "";
		}
		else {
			return _specificationValueUOM;
		}
	}

	@Override
	public void setSpecificationValueUOM(String specificationValueUOM) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specificationValueUOM = specificationValueUOM;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ipAddress = ipAddress;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProductSpecValueMap.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProductSpecValueMap.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProductSpecValueMap toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProductSpecValueMap>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProductSpecValueMapImpl productSpecValueMapImpl =
			new ProductSpecValueMapImpl();

		productSpecValueMapImpl.setUuid(getUuid());
		productSpecValueMapImpl.setProductSpecValueId(getProductSpecValueId());
		productSpecValueMapImpl.setGroupId(getGroupId());
		productSpecValueMapImpl.setProductSpecificationId(
			getProductSpecificationId());
		productSpecValueMapImpl.setSpecificationValueLabelId(
			getSpecificationValueLabelId());
		productSpecValueMapImpl.setSpecificationValueLabel(
			getSpecificationValueLabel());
		productSpecValueMapImpl.setSpecificationValueUOM(
			getSpecificationValueUOM());
		productSpecValueMapImpl.setCompanyId(getCompanyId());
		productSpecValueMapImpl.setUserId(getUserId());
		productSpecValueMapImpl.setUserName(getUserName());
		productSpecValueMapImpl.setCreatedBy(getCreatedBy());
		productSpecValueMapImpl.setModifiedBy(getModifiedBy());
		productSpecValueMapImpl.setCreateDate(getCreateDate());
		productSpecValueMapImpl.setModifiedDate(getModifiedDate());
		productSpecValueMapImpl.setIpAddress(getIpAddress());

		productSpecValueMapImpl.resetOriginalValues();

		return productSpecValueMapImpl;
	}

	@Override
	public ProductSpecValueMap cloneWithOriginalValues() {
		ProductSpecValueMapImpl productSpecValueMapImpl =
			new ProductSpecValueMapImpl();

		productSpecValueMapImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		productSpecValueMapImpl.setProductSpecValueId(
			this.<Long>getColumnOriginalValue("productSpecValueId"));
		productSpecValueMapImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		productSpecValueMapImpl.setProductSpecificationId(
			this.<Long>getColumnOriginalValue("productSpecificationId"));
		productSpecValueMapImpl.setSpecificationValueLabelId(
			this.<Long>getColumnOriginalValue("specificationValueLabelId"));
		productSpecValueMapImpl.setSpecificationValueLabel(
			this.<String>getColumnOriginalValue("specificationValueLabel"));
		productSpecValueMapImpl.setSpecificationValueUOM(
			this.<String>getColumnOriginalValue("specificationValueUOM"));
		productSpecValueMapImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		productSpecValueMapImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		productSpecValueMapImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		productSpecValueMapImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		productSpecValueMapImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		productSpecValueMapImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		productSpecValueMapImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		productSpecValueMapImpl.setIpAddress(
			this.<String>getColumnOriginalValue("ipAddress"));

		return productSpecValueMapImpl;
	}

	@Override
	public int compareTo(ProductSpecValueMap productSpecValueMap) {
		long primaryKey = productSpecValueMap.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProductSpecValueMap)) {
			return false;
		}

		ProductSpecValueMap productSpecValueMap = (ProductSpecValueMap)object;

		long primaryKey = productSpecValueMap.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProductSpecValueMap> toCacheModel() {
		ProductSpecValueMapCacheModel productSpecValueMapCacheModel =
			new ProductSpecValueMapCacheModel();

		productSpecValueMapCacheModel.uuid = getUuid();

		String uuid = productSpecValueMapCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			productSpecValueMapCacheModel.uuid = null;
		}

		productSpecValueMapCacheModel.productSpecValueId =
			getProductSpecValueId();

		productSpecValueMapCacheModel.groupId = getGroupId();

		productSpecValueMapCacheModel.productSpecificationId =
			getProductSpecificationId();

		productSpecValueMapCacheModel.specificationValueLabelId =
			getSpecificationValueLabelId();

		productSpecValueMapCacheModel.specificationValueLabel =
			getSpecificationValueLabel();

		String specificationValueLabel =
			productSpecValueMapCacheModel.specificationValueLabel;

		if ((specificationValueLabel != null) &&
			(specificationValueLabel.length() == 0)) {

			productSpecValueMapCacheModel.specificationValueLabel = null;
		}

		productSpecValueMapCacheModel.specificationValueUOM =
			getSpecificationValueUOM();

		String specificationValueUOM =
			productSpecValueMapCacheModel.specificationValueUOM;

		if ((specificationValueUOM != null) &&
			(specificationValueUOM.length() == 0)) {

			productSpecValueMapCacheModel.specificationValueUOM = null;
		}

		productSpecValueMapCacheModel.companyId = getCompanyId();

		productSpecValueMapCacheModel.userId = getUserId();

		productSpecValueMapCacheModel.userName = getUserName();

		String userName = productSpecValueMapCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			productSpecValueMapCacheModel.userName = null;
		}

		productSpecValueMapCacheModel.createdBy = getCreatedBy();

		productSpecValueMapCacheModel.modifiedBy = getModifiedBy();

		Date createDate = getCreateDate();

		if (createDate != null) {
			productSpecValueMapCacheModel.createDate = createDate.getTime();
		}
		else {
			productSpecValueMapCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			productSpecValueMapCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			productSpecValueMapCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		productSpecValueMapCacheModel.ipAddress = getIpAddress();

		String ipAddress = productSpecValueMapCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			productSpecValueMapCacheModel.ipAddress = null;
		}

		return productSpecValueMapCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProductSpecValueMap, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProductSpecValueMap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductSpecValueMap, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProductSpecValueMap)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProductSpecValueMap>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProductSpecValueMap.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _productSpecValueId;
	private long _groupId;
	private long _productSpecificationId;
	private long _specificationValueLabelId;
	private String _specificationValueLabel;
	private String _specificationValueUOM;
	private long _companyId;
	private long _userId;
	private String _userName;
	private long _createdBy;
	private long _modifiedBy;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _ipAddress;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProductSpecValueMap, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProductSpecValueMap)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("productSpecValueId", _productSpecValueId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put(
			"productSpecificationId", _productSpecificationId);
		_columnOriginalValues.put(
			"specificationValueLabelId", _specificationValueLabelId);
		_columnOriginalValues.put(
			"specificationValueLabel", _specificationValueLabel);
		_columnOriginalValues.put(
			"specificationValueUOM", _specificationValueUOM);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("ipAddress", _ipAddress);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("productSpecValueId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("productSpecificationId", 8L);

		columnBitmasks.put("specificationValueLabelId", 16L);

		columnBitmasks.put("specificationValueLabel", 32L);

		columnBitmasks.put("specificationValueUOM", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createdBy", 1024L);

		columnBitmasks.put("modifiedBy", 2048L);

		columnBitmasks.put("createDate", 4096L);

		columnBitmasks.put("modifiedDate", 8192L);

		columnBitmasks.put("ipAddress", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProductSpecValueMap _escapedModel;

}