/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.specification.category.map.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SpecCategoryMap service. Represents a row in the &quot;marketplace_speccategorymap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.marketplace.specification.category.map.model.impl.SpecCategoryMapModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.marketplace.specification.category.map.model.impl.SpecCategoryMapImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SpecCategoryMap
 * @generated
 */
@ProviderType
public interface SpecCategoryMapModel
	extends BaseModel<SpecCategoryMap>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a spec category map model instance should use the {@link SpecCategoryMap} interface instead.
	 */

	/**
	 * Returns the primary key of this spec category map.
	 *
	 * @return the primary key of this spec category map
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this spec category map.
	 *
	 * @param primaryKey the primary key of this spec category map
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this spec category map.
	 *
	 * @return the uuid of this spec category map
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this spec category map.
	 *
	 * @param uuid the uuid of this spec category map
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the spec category map ID of this spec category map.
	 *
	 * @return the spec category map ID of this spec category map
	 */
	public long getSpecCategoryMapId();

	/**
	 * Sets the spec category map ID of this spec category map.
	 *
	 * @param specCategoryMapId the spec category map ID of this spec category map
	 */
	public void setSpecCategoryMapId(long specCategoryMapId);

	/**
	 * Returns the specification ID of this spec category map.
	 *
	 * @return the specification ID of this spec category map
	 */
	public long getSpecificationId();

	/**
	 * Sets the specification ID of this spec category map.
	 *
	 * @param specificationId the specification ID of this spec category map
	 */
	public void setSpecificationId(long specificationId);

	/**
	 * Returns the category ID of this spec category map.
	 *
	 * @return the category ID of this spec category map
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this spec category map.
	 *
	 * @param categoryId the category ID of this spec category map
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the is category mandatory of this spec category map.
	 *
	 * @return the is category mandatory of this spec category map
	 */
	public boolean getIsCategoryMandatory();

	/**
	 * Returns <code>true</code> if this spec category map is is category mandatory.
	 *
	 * @return <code>true</code> if this spec category map is is category mandatory; <code>false</code> otherwise
	 */
	public boolean isIsCategoryMandatory();

	/**
	 * Sets whether this spec category map is is category mandatory.
	 *
	 * @param isCategoryMandatory the is category mandatory of this spec category map
	 */
	public void setIsCategoryMandatory(boolean isCategoryMandatory);

	/**
	 * Returns the company ID of this spec category map.
	 *
	 * @return the company ID of this spec category map
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this spec category map.
	 *
	 * @param companyId the company ID of this spec category map
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this spec category map.
	 *
	 * @return the create date of this spec category map
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this spec category map.
	 *
	 * @param createDate the create date of this spec category map
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this spec category map.
	 *
	 * @return the modified date of this spec category map
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this spec category map.
	 *
	 * @param modifiedDate the modified date of this spec category map
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this spec category map.
	 *
	 * @return the created by of this spec category map
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this spec category map.
	 *
	 * @param createdBy the created by of this spec category map
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this spec category map.
	 *
	 * @return the modified by of this spec category map
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this spec category map.
	 *
	 * @param modifiedBy the modified by of this spec category map
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the ip address of this spec category map.
	 *
	 * @return the ip address of this spec category map
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this spec category map.
	 *
	 * @param ipAddress the ip address of this spec category map
	 */
	public void setIpAddress(String ipAddress);

	@Override
	public SpecCategoryMap cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}