create table marketplace_specification (
	uuid_ VARCHAR(75) null,
	specificationId LONG not null primary key,
	groupId LONG,
	specificationLabel VARCHAR(75) null,
	specificationDescription VARCHAR(200) null,
	specificationFieldType LONG,
	specificationFieldDataType LONG,
	specificationPriority LONG,
	isVariant BOOLEAN,
	specificationGroupId LONG,
	cpSpecificationId LONG,
	specificationStatus VARCHAR(75) null,
	ipAddress VARCHAR(75) null,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	createdBy LONG,
	modifiedBy LONG
);