/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.variant.values.master.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the VariantValue service. Represents a row in the &quot;marketplace_variant_value&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.marketplace.variant.values.master.model.impl.VariantValueModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.marketplace.variant.values.master.model.impl.VariantValueImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VariantValue
 * @generated
 */
@ProviderType
public interface VariantValueModel
	extends BaseModel<VariantValue>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a variant value model instance should use the {@link VariantValue} interface instead.
	 */

	/**
	 * Returns the primary key of this variant value.
	 *
	 * @return the primary key of this variant value
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this variant value.
	 *
	 * @param primaryKey the primary key of this variant value
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this variant value.
	 *
	 * @return the uuid of this variant value
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this variant value.
	 *
	 * @param uuid the uuid of this variant value
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the variant value ID of this variant value.
	 *
	 * @return the variant value ID of this variant value
	 */
	public long getVariantValueId();

	/**
	 * Sets the variant value ID of this variant value.
	 *
	 * @param variantValueId the variant value ID of this variant value
	 */
	public void setVariantValueId(long variantValueId);

	/**
	 * Returns the group ID of this variant value.
	 *
	 * @return the group ID of this variant value
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this variant value.
	 *
	 * @param groupId the group ID of this variant value
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the product variant ID of this variant value.
	 *
	 * @return the product variant ID of this variant value
	 */
	public long getProductVariantId();

	/**
	 * Sets the product variant ID of this variant value.
	 *
	 * @param productVariantId the product variant ID of this variant value
	 */
	public void setProductVariantId(long productVariantId);

	/**
	 * Returns the variant val of this variant value.
	 *
	 * @return the variant val of this variant value
	 */
	@AutoEscape
	public String getVariantVal();

	/**
	 * Sets the variant val of this variant value.
	 *
	 * @param variantVal the variant val of this variant value
	 */
	public void setVariantVal(String variantVal);

	/**
	 * Returns the draft product ID of this variant value.
	 *
	 * @return the draft product ID of this variant value
	 */
	public long getDraftProductId();

	/**
	 * Sets the draft product ID of this variant value.
	 *
	 * @param draftProductId the draft product ID of this variant value
	 */
	public void setDraftProductId(long draftProductId);

	/**
	 * Returns the company ID of this variant value.
	 *
	 * @return the company ID of this variant value
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this variant value.
	 *
	 * @param companyId the company ID of this variant value
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this variant value.
	 *
	 * @return the user ID of this variant value
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this variant value.
	 *
	 * @param userId the user ID of this variant value
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this variant value.
	 *
	 * @return the user uuid of this variant value
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this variant value.
	 *
	 * @param userUuid the user uuid of this variant value
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this variant value.
	 *
	 * @return the user name of this variant value
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this variant value.
	 *
	 * @param userName the user name of this variant value
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this variant value.
	 *
	 * @return the create date of this variant value
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this variant value.
	 *
	 * @param createDate the create date of this variant value
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this variant value.
	 *
	 * @return the created by of this variant value
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this variant value.
	 *
	 * @param createdBy the created by of this variant value
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this variant value.
	 *
	 * @return the modified date of this variant value
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this variant value.
	 *
	 * @param modifiedDate the modified date of this variant value
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this variant value.
	 *
	 * @return the modified by of this variant value
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this variant value.
	 *
	 * @param modifiedBy the modified by of this variant value
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the ip address of this variant value.
	 *
	 * @return the ip address of this variant value
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this variant value.
	 *
	 * @param ipAddress the ip address of this variant value
	 */
	public void setIpAddress(String ipAddress);

	@Override
	public VariantValue cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}