/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.checkout.master.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CheckoutCustom service. Represents a row in the &quot;marketplace_checkout&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.marketplace.checkout.master.model.impl.CheckoutCustomModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.marketplace.checkout.master.model.impl.CheckoutCustomImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CheckoutCustom
 * @generated
 */
@ProviderType
public interface CheckoutCustomModel extends BaseModel<CheckoutCustom> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a checkout custom model instance should use the {@link CheckoutCustom} interface instead.
	 */

	/**
	 * Returns the primary key of this checkout custom.
	 *
	 * @return the primary key of this checkout custom
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this checkout custom.
	 *
	 * @param primaryKey the primary key of this checkout custom
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the checkout custom ID of this checkout custom.
	 *
	 * @return the checkout custom ID of this checkout custom
	 */
	public long getCheckoutCustomId();

	/**
	 * Sets the checkout custom ID of this checkout custom.
	 *
	 * @param checkoutCustomId the checkout custom ID of this checkout custom
	 */
	public void setCheckoutCustomId(long checkoutCustomId);

	/**
	 * Returns the commerce order ID of this checkout custom.
	 *
	 * @return the commerce order ID of this checkout custom
	 */
	public long getCommerceOrderId();

	/**
	 * Sets the commerce order ID of this checkout custom.
	 *
	 * @param commerceOrderId the commerce order ID of this checkout custom
	 */
	public void setCommerceOrderId(long commerceOrderId);

	/**
	 * Returns the request json of this checkout custom.
	 *
	 * @return the request json of this checkout custom
	 */
	@AutoEscape
	public String getRequestJson();

	/**
	 * Sets the request json of this checkout custom.
	 *
	 * @param requestJson the request json of this checkout custom
	 */
	public void setRequestJson(String requestJson);

	/**
	 * Returns the response json of this checkout custom.
	 *
	 * @return the response json of this checkout custom
	 */
	@AutoEscape
	public String getResponseJson();

	/**
	 * Sets the response json of this checkout custom.
	 *
	 * @param responseJson the response json of this checkout custom
	 */
	public void setResponseJson(String responseJson);

	/**
	 * Returns the module of this checkout custom.
	 *
	 * @return the module of this checkout custom
	 */
	@AutoEscape
	public String getModule();

	/**
	 * Sets the module of this checkout custom.
	 *
	 * @param module the module of this checkout custom
	 */
	public void setModule(String module);

	/**
	 * Returns the create date of this checkout custom.
	 *
	 * @return the create date of this checkout custom
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this checkout custom.
	 *
	 * @param createDate the create date of this checkout custom
	 */
	public void setCreateDate(Date createDate);

	@Override
	public CheckoutCustom cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}