/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.product.pkg.content.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductPackageContent service. Represents a row in the &quot;marketplace_prod_pkg_content&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.marketplace.product.pkg.content.model.impl.ProductPackageContentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.marketplace.product.pkg.content.model.impl.ProductPackageContentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductPackageContent
 * @generated
 */
@ProviderType
public interface ProductPackageContentModel
	extends BaseModel<ProductPackageContent>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product package content model instance should use the {@link ProductPackageContent} interface instead.
	 */

	/**
	 * Returns the primary key of this product package content.
	 *
	 * @return the primary key of this product package content
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product package content.
	 *
	 * @param primaryKey the primary key of this product package content
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product package content.
	 *
	 * @return the uuid of this product package content
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this product package content.
	 *
	 * @param uuid the uuid of this product package content
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the package content ID of this product package content.
	 *
	 * @return the package content ID of this product package content
	 */
	public long getPackageContentId();

	/**
	 * Sets the package content ID of this product package content.
	 *
	 * @param packageContentId the package content ID of this product package content
	 */
	public void setPackageContentId(long packageContentId);

	/**
	 * Returns the group ID of this product package content.
	 *
	 * @return the group ID of this product package content
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this product package content.
	 *
	 * @param groupId the group ID of this product package content
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the item name of this product package content.
	 *
	 * @return the item name of this product package content
	 */
	@AutoEscape
	public String getItemName();

	/**
	 * Sets the item name of this product package content.
	 *
	 * @param itemName the item name of this product package content
	 */
	public void setItemName(String itemName);

	/**
	 * Returns the item quantity of this product package content.
	 *
	 * @return the item quantity of this product package content
	 */
	@AutoEscape
	public String getItemQuantity();

	/**
	 * Sets the item quantity of this product package content.
	 *
	 * @param itemQuantity the item quantity of this product package content
	 */
	public void setItemQuantity(String itemQuantity);

	/**
	 * Returns the draft product ID of this product package content.
	 *
	 * @return the draft product ID of this product package content
	 */
	public long getDraftProductId();

	/**
	 * Sets the draft product ID of this product package content.
	 *
	 * @param draftProductId the draft product ID of this product package content
	 */
	public void setDraftProductId(long draftProductId);

	/**
	 * Returns the company ID of this product package content.
	 *
	 * @return the company ID of this product package content
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product package content.
	 *
	 * @param companyId the company ID of this product package content
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product package content.
	 *
	 * @return the user ID of this product package content
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this product package content.
	 *
	 * @param userId the user ID of this product package content
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product package content.
	 *
	 * @return the user uuid of this product package content
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this product package content.
	 *
	 * @param userUuid the user uuid of this product package content
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this product package content.
	 *
	 * @return the user name of this product package content
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this product package content.
	 *
	 * @param userName the user name of this product package content
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the created by of this product package content.
	 *
	 * @return the created by of this product package content
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this product package content.
	 *
	 * @param createdBy the created by of this product package content
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this product package content.
	 *
	 * @return the modified by of this product package content
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this product package content.
	 *
	 * @param modifiedBy the modified by of this product package content
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the create date of this product package content.
	 *
	 * @return the create date of this product package content
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product package content.
	 *
	 * @param createDate the create date of this product package content
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product package content.
	 *
	 * @return the modified date of this product package content
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product package content.
	 *
	 * @param modifiedDate the modified date of this product package content
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ip address of this product package content.
	 *
	 * @return the ip address of this product package content
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this product package content.
	 *
	 * @param ipAddress the ip address of this product package content
	 */
	public void setIpAddress(String ipAddress);

	@Override
	public ProductPackageContent cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}