/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.product.search.keywords.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.marketplace.product.search.keywords.model.ProductSearchKeywords;
import com.marketplace.product.search.keywords.model.ProductSearchKeywordsModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProductSearchKeywords service. Represents a row in the &quot;marketplace_product_keywords&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProductSearchKeywordsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductSearchKeywordsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductSearchKeywordsImpl
 * @generated
 */
public class ProductSearchKeywordsModelImpl
	extends BaseModelImpl<ProductSearchKeywords>
	implements ProductSearchKeywordsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product search keywords model instance should use the <code>ProductSearchKeywords</code> interface instead.
	 */
	public static final String TABLE_NAME = "marketplace_product_keywords";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"searchKeywordId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"searchKeyword", Types.VARCHAR},
		{"draftProductId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"ipAddress", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("searchKeywordId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("searchKeyword", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("draftProductId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table marketplace_product_keywords (uuid_ VARCHAR(75) null,searchKeywordId LONG not null primary key,groupId LONG,searchKeyword VARCHAR(75) null,draftProductId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createdBy LONG,modifiedBy LONG,createDate DATE null,modifiedDate DATE null,ipAddress VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table marketplace_product_keywords";

	public static final String ORDER_BY_JPQL =
		" ORDER BY productSearchKeywords.searchKeywordId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY marketplace_product_keywords.searchKeywordId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DRAFTPRODUCTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SEARCHKEYWORDID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProductSearchKeywordsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _searchKeywordId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSearchKeywordId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _searchKeywordId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProductSearchKeywords.class;
	}

	@Override
	public String getModelClassName() {
		return ProductSearchKeywords.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProductSearchKeywords, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProductSearchKeywords, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductSearchKeywords, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProductSearchKeywords)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProductSearchKeywords, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProductSearchKeywords, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProductSearchKeywords)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProductSearchKeywords, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProductSearchKeywords, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ProductSearchKeywords, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProductSearchKeywords, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProductSearchKeywords, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProductSearchKeywords, Object>>();
		Map<String, BiConsumer<ProductSearchKeywords, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ProductSearchKeywords, ?>>();

		attributeGetterFunctions.put("uuid", ProductSearchKeywords::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProductSearchKeywords, String>)
				ProductSearchKeywords::setUuid);
		attributeGetterFunctions.put(
			"searchKeywordId", ProductSearchKeywords::getSearchKeywordId);
		attributeSetterBiConsumers.put(
			"searchKeywordId",
			(BiConsumer<ProductSearchKeywords, Long>)
				ProductSearchKeywords::setSearchKeywordId);
		attributeGetterFunctions.put(
			"groupId", ProductSearchKeywords::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProductSearchKeywords, Long>)
				ProductSearchKeywords::setGroupId);
		attributeGetterFunctions.put(
			"searchKeyword", ProductSearchKeywords::getSearchKeyword);
		attributeSetterBiConsumers.put(
			"searchKeyword",
			(BiConsumer<ProductSearchKeywords, String>)
				ProductSearchKeywords::setSearchKeyword);
		attributeGetterFunctions.put(
			"draftProductId", ProductSearchKeywords::getDraftProductId);
		attributeSetterBiConsumers.put(
			"draftProductId",
			(BiConsumer<ProductSearchKeywords, Long>)
				ProductSearchKeywords::setDraftProductId);
		attributeGetterFunctions.put(
			"companyId", ProductSearchKeywords::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProductSearchKeywords, Long>)
				ProductSearchKeywords::setCompanyId);
		attributeGetterFunctions.put(
			"userId", ProductSearchKeywords::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ProductSearchKeywords, Long>)
				ProductSearchKeywords::setUserId);
		attributeGetterFunctions.put(
			"userName", ProductSearchKeywords::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ProductSearchKeywords, String>)
				ProductSearchKeywords::setUserName);
		attributeGetterFunctions.put(
			"createdBy", ProductSearchKeywords::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ProductSearchKeywords, Long>)
				ProductSearchKeywords::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", ProductSearchKeywords::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ProductSearchKeywords, Long>)
				ProductSearchKeywords::setModifiedBy);
		attributeGetterFunctions.put(
			"createDate", ProductSearchKeywords::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProductSearchKeywords, Date>)
				ProductSearchKeywords::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ProductSearchKeywords::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProductSearchKeywords, Date>)
				ProductSearchKeywords::setModifiedDate);
		attributeGetterFunctions.put(
			"ipAddress", ProductSearchKeywords::getIpAddress);
		attributeSetterBiConsumers.put(
			"ipAddress",
			(BiConsumer<ProductSearchKeywords, String>)
				ProductSearchKeywords::setIpAddress);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getSearchKeywordId() {
		return _searchKeywordId;
	}

	@Override
	public void setSearchKeywordId(long searchKeywordId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_searchKeywordId = searchKeywordId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public String getSearchKeyword() {
		if (_searchKeyword == null) {
			return "";
		}
		else {
			return _searchKeyword;
		}
	}

	@Override
	public void setSearchKeyword(String searchKeyword) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_searchKeyword = searchKeyword;
	}

	@Override
	public long getDraftProductId() {
		return _draftProductId;
	}

	@Override
	public void setDraftProductId(long draftProductId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_draftProductId = draftProductId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDraftProductId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("draftProductId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ipAddress = ipAddress;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProductSearchKeywords.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProductSearchKeywords.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProductSearchKeywords toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProductSearchKeywords>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProductSearchKeywordsImpl productSearchKeywordsImpl =
			new ProductSearchKeywordsImpl();

		productSearchKeywordsImpl.setUuid(getUuid());
		productSearchKeywordsImpl.setSearchKeywordId(getSearchKeywordId());
		productSearchKeywordsImpl.setGroupId(getGroupId());
		productSearchKeywordsImpl.setSearchKeyword(getSearchKeyword());
		productSearchKeywordsImpl.setDraftProductId(getDraftProductId());
		productSearchKeywordsImpl.setCompanyId(getCompanyId());
		productSearchKeywordsImpl.setUserId(getUserId());
		productSearchKeywordsImpl.setUserName(getUserName());
		productSearchKeywordsImpl.setCreatedBy(getCreatedBy());
		productSearchKeywordsImpl.setModifiedBy(getModifiedBy());
		productSearchKeywordsImpl.setCreateDate(getCreateDate());
		productSearchKeywordsImpl.setModifiedDate(getModifiedDate());
		productSearchKeywordsImpl.setIpAddress(getIpAddress());

		productSearchKeywordsImpl.resetOriginalValues();

		return productSearchKeywordsImpl;
	}

	@Override
	public ProductSearchKeywords cloneWithOriginalValues() {
		ProductSearchKeywordsImpl productSearchKeywordsImpl =
			new ProductSearchKeywordsImpl();

		productSearchKeywordsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		productSearchKeywordsImpl.setSearchKeywordId(
			this.<Long>getColumnOriginalValue("searchKeywordId"));
		productSearchKeywordsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		productSearchKeywordsImpl.setSearchKeyword(
			this.<String>getColumnOriginalValue("searchKeyword"));
		productSearchKeywordsImpl.setDraftProductId(
			this.<Long>getColumnOriginalValue("draftProductId"));
		productSearchKeywordsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		productSearchKeywordsImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		productSearchKeywordsImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		productSearchKeywordsImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		productSearchKeywordsImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		productSearchKeywordsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		productSearchKeywordsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		productSearchKeywordsImpl.setIpAddress(
			this.<String>getColumnOriginalValue("ipAddress"));

		return productSearchKeywordsImpl;
	}

	@Override
	public int compareTo(ProductSearchKeywords productSearchKeywords) {
		long primaryKey = productSearchKeywords.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProductSearchKeywords)) {
			return false;
		}

		ProductSearchKeywords productSearchKeywords =
			(ProductSearchKeywords)object;

		long primaryKey = productSearchKeywords.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProductSearchKeywords> toCacheModel() {
		ProductSearchKeywordsCacheModel productSearchKeywordsCacheModel =
			new ProductSearchKeywordsCacheModel();

		productSearchKeywordsCacheModel.uuid = getUuid();

		String uuid = productSearchKeywordsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			productSearchKeywordsCacheModel.uuid = null;
		}

		productSearchKeywordsCacheModel.searchKeywordId = getSearchKeywordId();

		productSearchKeywordsCacheModel.groupId = getGroupId();

		productSearchKeywordsCacheModel.searchKeyword = getSearchKeyword();

		String searchKeyword = productSearchKeywordsCacheModel.searchKeyword;

		if ((searchKeyword != null) && (searchKeyword.length() == 0)) {
			productSearchKeywordsCacheModel.searchKeyword = null;
		}

		productSearchKeywordsCacheModel.draftProductId = getDraftProductId();

		productSearchKeywordsCacheModel.companyId = getCompanyId();

		productSearchKeywordsCacheModel.userId = getUserId();

		productSearchKeywordsCacheModel.userName = getUserName();

		String userName = productSearchKeywordsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			productSearchKeywordsCacheModel.userName = null;
		}

		productSearchKeywordsCacheModel.createdBy = getCreatedBy();

		productSearchKeywordsCacheModel.modifiedBy = getModifiedBy();

		Date createDate = getCreateDate();

		if (createDate != null) {
			productSearchKeywordsCacheModel.createDate = createDate.getTime();
		}
		else {
			productSearchKeywordsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			productSearchKeywordsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			productSearchKeywordsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		productSearchKeywordsCacheModel.ipAddress = getIpAddress();

		String ipAddress = productSearchKeywordsCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			productSearchKeywordsCacheModel.ipAddress = null;
		}

		return productSearchKeywordsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProductSearchKeywords, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProductSearchKeywords, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductSearchKeywords, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProductSearchKeywords)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProductSearchKeywords>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProductSearchKeywords.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _searchKeywordId;
	private long _groupId;
	private String _searchKeyword;
	private long _draftProductId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private long _createdBy;
	private long _modifiedBy;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _ipAddress;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProductSearchKeywords, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProductSearchKeywords)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("searchKeywordId", _searchKeywordId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("searchKeyword", _searchKeyword);
		_columnOriginalValues.put("draftProductId", _draftProductId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("ipAddress", _ipAddress);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("searchKeywordId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("searchKeyword", 8L);

		columnBitmasks.put("draftProductId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createdBy", 256L);

		columnBitmasks.put("modifiedBy", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("ipAddress", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProductSearchKeywords _escapedModel;

}