/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.product.mediasku.master.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.marketplace.product.mediasku.master.model.ProductMediaSKU;
import com.marketplace.product.mediasku.master.model.ProductMediaSKUModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProductMediaSKU service. Represents a row in the &quot;marketplace_product_mediasku&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProductMediaSKUModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductMediaSKUImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductMediaSKUImpl
 * @generated
 */
public class ProductMediaSKUModelImpl
	extends BaseModelImpl<ProductMediaSKU> implements ProductMediaSKUModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product media sku model instance should use the <code>ProductMediaSKU</code> interface instead.
	 */
	public static final String TABLE_NAME = "marketplace_product_mediasku";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"ProductMediaSKUId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"createdBy", Types.BIGINT},
		{"modifiedDate", Types.TIMESTAMP}, {"modifiedBy", Types.BIGINT},
		{"ipAddress", Types.VARCHAR}, {"draftProductId", Types.BIGINT},
		{"productSKUId", Types.BIGINT}, {"imageUrl", Types.VARCHAR},
		{"fileEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ProductMediaSKUId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("draftProductId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productSKUId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("imageUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table marketplace_product_mediasku (uuid_ VARCHAR(75) null,ProductMediaSKUId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,createdBy LONG,modifiedDate DATE null,modifiedBy LONG,ipAddress VARCHAR(75) null,draftProductId LONG,productSKUId LONG,imageUrl VARCHAR(255) null,fileEntryId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table marketplace_product_mediasku";

	public static final String ORDER_BY_JPQL =
		" ORDER BY productMediaSKU.ProductMediaSKUId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY marketplace_product_mediasku.ProductMediaSKUId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DRAFTPRODUCTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRODUCTSKUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRODUCTMEDIASKUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProductMediaSKUModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ProductMediaSKUId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProductMediaSKUId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ProductMediaSKUId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProductMediaSKU.class;
	}

	@Override
	public String getModelClassName() {
		return ProductMediaSKU.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProductMediaSKU, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProductMediaSKU, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductMediaSKU, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProductMediaSKU)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProductMediaSKU, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProductMediaSKU, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProductMediaSKU)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProductMediaSKU, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProductMediaSKU, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ProductMediaSKU, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProductMediaSKU, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProductMediaSKU, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ProductMediaSKU, Object>>();
		Map<String, BiConsumer<ProductMediaSKU, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ProductMediaSKU, ?>>();

		attributeGetterFunctions.put("uuid", ProductMediaSKU::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProductMediaSKU, String>)ProductMediaSKU::setUuid);
		attributeGetterFunctions.put(
			"ProductMediaSKUId", ProductMediaSKU::getProductMediaSKUId);
		attributeSetterBiConsumers.put(
			"ProductMediaSKUId",
			(BiConsumer<ProductMediaSKU, Long>)
				ProductMediaSKU::setProductMediaSKUId);
		attributeGetterFunctions.put("groupId", ProductMediaSKU::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProductMediaSKU, Long>)ProductMediaSKU::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ProductMediaSKU::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProductMediaSKU, Long>)ProductMediaSKU::setCompanyId);
		attributeGetterFunctions.put("userId", ProductMediaSKU::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ProductMediaSKU, Long>)ProductMediaSKU::setUserId);
		attributeGetterFunctions.put("userName", ProductMediaSKU::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ProductMediaSKU, String>)ProductMediaSKU::setUserName);
		attributeGetterFunctions.put(
			"createDate", ProductMediaSKU::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProductMediaSKU, Date>)ProductMediaSKU::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", ProductMediaSKU::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ProductMediaSKU, Long>)ProductMediaSKU::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", ProductMediaSKU::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProductMediaSKU, Date>)
				ProductMediaSKU::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", ProductMediaSKU::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ProductMediaSKU, Long>)ProductMediaSKU::setModifiedBy);
		attributeGetterFunctions.put(
			"ipAddress", ProductMediaSKU::getIpAddress);
		attributeSetterBiConsumers.put(
			"ipAddress",
			(BiConsumer<ProductMediaSKU, String>)ProductMediaSKU::setIpAddress);
		attributeGetterFunctions.put(
			"draftProductId", ProductMediaSKU::getDraftProductId);
		attributeSetterBiConsumers.put(
			"draftProductId",
			(BiConsumer<ProductMediaSKU, Long>)
				ProductMediaSKU::setDraftProductId);
		attributeGetterFunctions.put(
			"productSKUId", ProductMediaSKU::getProductSKUId);
		attributeSetterBiConsumers.put(
			"productSKUId",
			(BiConsumer<ProductMediaSKU, Long>)
				ProductMediaSKU::setProductSKUId);
		attributeGetterFunctions.put("imageUrl", ProductMediaSKU::getImageUrl);
		attributeSetterBiConsumers.put(
			"imageUrl",
			(BiConsumer<ProductMediaSKU, String>)ProductMediaSKU::setImageUrl);
		attributeGetterFunctions.put(
			"fileEntryId", ProductMediaSKU::getFileEntryId);
		attributeSetterBiConsumers.put(
			"fileEntryId",
			(BiConsumer<ProductMediaSKU, Long>)ProductMediaSKU::setFileEntryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getProductMediaSKUId() {
		return _ProductMediaSKUId;
	}

	@Override
	public void setProductMediaSKUId(long ProductMediaSKUId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ProductMediaSKUId = ProductMediaSKUId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ipAddress = ipAddress;
	}

	@Override
	public long getDraftProductId() {
		return _draftProductId;
	}

	@Override
	public void setDraftProductId(long draftProductId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_draftProductId = draftProductId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDraftProductId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("draftProductId"));
	}

	@Override
	public long getProductSKUId() {
		return _productSKUId;
	}

	@Override
	public void setProductSKUId(long productSKUId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productSKUId = productSKUId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProductSKUId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("productSKUId"));
	}

	@Override
	public String getImageUrl() {
		if (_imageUrl == null) {
			return "";
		}
		else {
			return _imageUrl;
		}
	}

	@Override
	public void setImageUrl(String imageUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageUrl = imageUrl;
	}

	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProductMediaSKU.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProductMediaSKU.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProductMediaSKU toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProductMediaSKU>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProductMediaSKUImpl productMediaSKUImpl = new ProductMediaSKUImpl();

		productMediaSKUImpl.setUuid(getUuid());
		productMediaSKUImpl.setProductMediaSKUId(getProductMediaSKUId());
		productMediaSKUImpl.setGroupId(getGroupId());
		productMediaSKUImpl.setCompanyId(getCompanyId());
		productMediaSKUImpl.setUserId(getUserId());
		productMediaSKUImpl.setUserName(getUserName());
		productMediaSKUImpl.setCreateDate(getCreateDate());
		productMediaSKUImpl.setCreatedBy(getCreatedBy());
		productMediaSKUImpl.setModifiedDate(getModifiedDate());
		productMediaSKUImpl.setModifiedBy(getModifiedBy());
		productMediaSKUImpl.setIpAddress(getIpAddress());
		productMediaSKUImpl.setDraftProductId(getDraftProductId());
		productMediaSKUImpl.setProductSKUId(getProductSKUId());
		productMediaSKUImpl.setImageUrl(getImageUrl());
		productMediaSKUImpl.setFileEntryId(getFileEntryId());

		productMediaSKUImpl.resetOriginalValues();

		return productMediaSKUImpl;
	}

	@Override
	public ProductMediaSKU cloneWithOriginalValues() {
		ProductMediaSKUImpl productMediaSKUImpl = new ProductMediaSKUImpl();

		productMediaSKUImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		productMediaSKUImpl.setProductMediaSKUId(
			this.<Long>getColumnOriginalValue("ProductMediaSKUId"));
		productMediaSKUImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		productMediaSKUImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		productMediaSKUImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		productMediaSKUImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		productMediaSKUImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		productMediaSKUImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		productMediaSKUImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		productMediaSKUImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		productMediaSKUImpl.setIpAddress(
			this.<String>getColumnOriginalValue("ipAddress"));
		productMediaSKUImpl.setDraftProductId(
			this.<Long>getColumnOriginalValue("draftProductId"));
		productMediaSKUImpl.setProductSKUId(
			this.<Long>getColumnOriginalValue("productSKUId"));
		productMediaSKUImpl.setImageUrl(
			this.<String>getColumnOriginalValue("imageUrl"));
		productMediaSKUImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));

		return productMediaSKUImpl;
	}

	@Override
	public int compareTo(ProductMediaSKU productMediaSKU) {
		long primaryKey = productMediaSKU.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProductMediaSKU)) {
			return false;
		}

		ProductMediaSKU productMediaSKU = (ProductMediaSKU)object;

		long primaryKey = productMediaSKU.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProductMediaSKU> toCacheModel() {
		ProductMediaSKUCacheModel productMediaSKUCacheModel =
			new ProductMediaSKUCacheModel();

		productMediaSKUCacheModel.uuid = getUuid();

		String uuid = productMediaSKUCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			productMediaSKUCacheModel.uuid = null;
		}

		productMediaSKUCacheModel.ProductMediaSKUId = getProductMediaSKUId();

		productMediaSKUCacheModel.groupId = getGroupId();

		productMediaSKUCacheModel.companyId = getCompanyId();

		productMediaSKUCacheModel.userId = getUserId();

		productMediaSKUCacheModel.userName = getUserName();

		String userName = productMediaSKUCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			productMediaSKUCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			productMediaSKUCacheModel.createDate = createDate.getTime();
		}
		else {
			productMediaSKUCacheModel.createDate = Long.MIN_VALUE;
		}

		productMediaSKUCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			productMediaSKUCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			productMediaSKUCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		productMediaSKUCacheModel.modifiedBy = getModifiedBy();

		productMediaSKUCacheModel.ipAddress = getIpAddress();

		String ipAddress = productMediaSKUCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			productMediaSKUCacheModel.ipAddress = null;
		}

		productMediaSKUCacheModel.draftProductId = getDraftProductId();

		productMediaSKUCacheModel.productSKUId = getProductSKUId();

		productMediaSKUCacheModel.imageUrl = getImageUrl();

		String imageUrl = productMediaSKUCacheModel.imageUrl;

		if ((imageUrl != null) && (imageUrl.length() == 0)) {
			productMediaSKUCacheModel.imageUrl = null;
		}

		productMediaSKUCacheModel.fileEntryId = getFileEntryId();

		return productMediaSKUCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProductMediaSKU, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProductMediaSKU, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductMediaSKU, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ProductMediaSKU)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProductMediaSKU>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProductMediaSKU.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _ProductMediaSKUId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private String _ipAddress;
	private long _draftProductId;
	private long _productSKUId;
	private String _imageUrl;
	private long _fileEntryId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProductMediaSKU, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProductMediaSKU)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("ProductMediaSKUId", _ProductMediaSKUId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("ipAddress", _ipAddress);
		_columnOriginalValues.put("draftProductId", _draftProductId);
		_columnOriginalValues.put("productSKUId", _productSKUId);
		_columnOriginalValues.put("imageUrl", _imageUrl);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("ProductMediaSKUId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("createdBy", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("modifiedBy", 512L);

		columnBitmasks.put("ipAddress", 1024L);

		columnBitmasks.put("draftProductId", 2048L);

		columnBitmasks.put("productSKUId", 4096L);

		columnBitmasks.put("imageUrl", 8192L);

		columnBitmasks.put("fileEntryId", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProductMediaSKU _escapedModel;

}