/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.checkout.consignee.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CheckoutConsigneeDetails service. Represents a row in the &quot;marketplace_consigneedetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.marketplace.checkout.consignee.model.impl.CheckoutConsigneeDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.marketplace.checkout.consignee.model.impl.CheckoutConsigneeDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CheckoutConsigneeDetails
 * @generated
 */
@ProviderType
public interface CheckoutConsigneeDetailsModel
	extends BaseModel<CheckoutConsigneeDetails>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a checkout consignee details model instance should use the {@link CheckoutConsigneeDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this checkout consignee details.
	 *
	 * @return the primary key of this checkout consignee details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this checkout consignee details.
	 *
	 * @param primaryKey the primary key of this checkout consignee details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this checkout consignee details.
	 *
	 * @return the uuid of this checkout consignee details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this checkout consignee details.
	 *
	 * @param uuid the uuid of this checkout consignee details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the checkout consignee ID of this checkout consignee details.
	 *
	 * @return the checkout consignee ID of this checkout consignee details
	 */
	public long getCheckoutConsigneeId();

	/**
	 * Sets the checkout consignee ID of this checkout consignee details.
	 *
	 * @param checkoutConsigneeId the checkout consignee ID of this checkout consignee details
	 */
	public void setCheckoutConsigneeId(long checkoutConsigneeId);

	/**
	 * Returns the group ID of this checkout consignee details.
	 *
	 * @return the group ID of this checkout consignee details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this checkout consignee details.
	 *
	 * @param groupId the group ID of this checkout consignee details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this checkout consignee details.
	 *
	 * @return the company ID of this checkout consignee details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this checkout consignee details.
	 *
	 * @param companyId the company ID of this checkout consignee details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this checkout consignee details.
	 *
	 * @return the user ID of this checkout consignee details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this checkout consignee details.
	 *
	 * @param userId the user ID of this checkout consignee details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this checkout consignee details.
	 *
	 * @return the user uuid of this checkout consignee details
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this checkout consignee details.
	 *
	 * @param userUuid the user uuid of this checkout consignee details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this checkout consignee details.
	 *
	 * @return the user name of this checkout consignee details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this checkout consignee details.
	 *
	 * @param userName the user name of this checkout consignee details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the created by of this checkout consignee details.
	 *
	 * @return the created by of this checkout consignee details
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this checkout consignee details.
	 *
	 * @param createdBy the created by of this checkout consignee details
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this checkout consignee details.
	 *
	 * @return the modified by of this checkout consignee details
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this checkout consignee details.
	 *
	 * @param modifiedBy the modified by of this checkout consignee details
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the create date of this checkout consignee details.
	 *
	 * @return the create date of this checkout consignee details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this checkout consignee details.
	 *
	 * @param createDate the create date of this checkout consignee details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this checkout consignee details.
	 *
	 * @return the modified date of this checkout consignee details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this checkout consignee details.
	 *
	 * @param modifiedDate the modified date of this checkout consignee details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the parent cart ID of this checkout consignee details.
	 *
	 * @return the parent cart ID of this checkout consignee details
	 */
	public long getParentCartId();

	/**
	 * Sets the parent cart ID of this checkout consignee details.
	 *
	 * @param parentCartId the parent cart ID of this checkout consignee details
	 */
	public void setParentCartId(long parentCartId);

	/**
	 * Returns the order item ID of this checkout consignee details.
	 *
	 * @return the order item ID of this checkout consignee details
	 */
	public long getOrderItemId();

	/**
	 * Sets the order item ID of this checkout consignee details.
	 *
	 * @param orderItemId the order item ID of this checkout consignee details
	 */
	public void setOrderItemId(long orderItemId);

	/**
	 * Returns the shipping consignee ID of this checkout consignee details.
	 *
	 * @return the shipping consignee ID of this checkout consignee details
	 */
	@AutoEscape
	public String getShippingConsigneeId();

	/**
	 * Sets the shipping consignee ID of this checkout consignee details.
	 *
	 * @param shippingConsigneeId the shipping consignee ID of this checkout consignee details
	 */
	public void setShippingConsigneeId(String shippingConsigneeId);

	/**
	 * Returns the ship consignee json of this checkout consignee details.
	 *
	 * @return the ship consignee json of this checkout consignee details
	 */
	@AutoEscape
	public String getShipConsigneeJson();

	/**
	 * Sets the ship consignee json of this checkout consignee details.
	 *
	 * @param shipConsigneeJson the ship consignee json of this checkout consignee details
	 */
	public void setShipConsigneeJson(String shipConsigneeJson);

	/**
	 * Returns the ship consignee address ID of this checkout consignee details.
	 *
	 * @return the ship consignee address ID of this checkout consignee details
	 */
	@AutoEscape
	public String getShipConsigneeAddressID();

	/**
	 * Sets the ship consignee address ID of this checkout consignee details.
	 *
	 * @param shipConsigneeAddressID the ship consignee address ID of this checkout consignee details
	 */
	public void setShipConsigneeAddressID(String shipConsigneeAddressID);

	/**
	 * Returns the ship consignee address json of this checkout consignee details.
	 *
	 * @return the ship consignee address json of this checkout consignee details
	 */
	@AutoEscape
	public String getShipConsigneeAddressJson();

	/**
	 * Sets the ship consignee address json of this checkout consignee details.
	 *
	 * @param shipConsigneeAddressJson the ship consignee address json of this checkout consignee details
	 */
	public void setShipConsigneeAddressJson(String shipConsigneeAddressJson);

	/**
	 * Returns the billing consignee ID of this checkout consignee details.
	 *
	 * @return the billing consignee ID of this checkout consignee details
	 */
	@AutoEscape
	public String getBillingConsigneeId();

	/**
	 * Sets the billing consignee ID of this checkout consignee details.
	 *
	 * @param billingConsigneeId the billing consignee ID of this checkout consignee details
	 */
	public void setBillingConsigneeId(String billingConsigneeId);

	/**
	 * Returns the bill consignee json of this checkout consignee details.
	 *
	 * @return the bill consignee json of this checkout consignee details
	 */
	@AutoEscape
	public String getBillConsigneeJson();

	/**
	 * Sets the bill consignee json of this checkout consignee details.
	 *
	 * @param billConsigneeJson the bill consignee json of this checkout consignee details
	 */
	public void setBillConsigneeJson(String billConsigneeJson);

	/**
	 * Returns the bill consignee address ID of this checkout consignee details.
	 *
	 * @return the bill consignee address ID of this checkout consignee details
	 */
	@AutoEscape
	public String getBillConsigneeAddressId();

	/**
	 * Sets the bill consignee address ID of this checkout consignee details.
	 *
	 * @param billConsigneeAddressId the bill consignee address ID of this checkout consignee details
	 */
	public void setBillConsigneeAddressId(String billConsigneeAddressId);

	/**
	 * Returns the bill consignee address json of this checkout consignee details.
	 *
	 * @return the bill consignee address json of this checkout consignee details
	 */
	@AutoEscape
	public String getBillConsigneeAddressJson();

	/**
	 * Sets the bill consignee address json of this checkout consignee details.
	 *
	 * @param billConsigneeAddressJson the bill consignee address json of this checkout consignee details
	 */
	public void setBillConsigneeAddressJson(String billConsigneeAddressJson);

	/**
	 * Returns the quantity of this checkout consignee details.
	 *
	 * @return the quantity of this checkout consignee details
	 */
	public long getQuantity();

	/**
	 * Sets the quantity of this checkout consignee details.
	 *
	 * @param quantity the quantity of this checkout consignee details
	 */
	public void setQuantity(long quantity);

	@Override
	public CheckoutConsigneeDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}