create table marketplace_category (
	uuid_ VARCHAR(75) null,
	categoryId LONG not null primary key,
	parentCategoryId LONG,
	assetCategoryId LONG,
	groupId LONG,
	categoryName VARCHAR(75) null,
	categoryCode VARCHAR(75) null,
	categoryDescription VARCHAR(75) null,
	categoryType VARCHAR(75) null,
	assignManager LONG,
	assignReviewer LONG,
	categoryApprovalStatus VARCHAR(75) null,
	reviewerRemarks VARCHAR(75) null,
	categoryExpiryDate DATE null,
	categoryInactive BOOLEAN,
	externalReferenceId VARCHAR(75) null,
	categoryImageId LONG,
	categoryImageURL VARCHAR(75) null,
	managerRemarks VARCHAR(75) null,
	treePath VARCHAR(75) null,
	termsCondition VARCHAR(75) null,
	hasChild BOOLEAN,
	customAtr1 VARCHAR(75) null,
	customAtr2 VARCHAR(75) null,
	customAtr3 VARCHAR(75) null,
	customAtr4 VARCHAR(75) null,
	customAtr5 VARCHAR(75) null,
	customAtr6 VARCHAR(75) null,
	customAtr7 VARCHAR(75) null,
	customAtr8 VARCHAR(75) null,
	customAtr9 VARCHAR(75) null,
	customAtr10 VARCHAR(75) null,
	createdBy LONG,
	modifiedBy LONG,
	ipAddress VARCHAR(75) null,
	isActive BOOLEAN,
	downForSeller BOOLEAN,
	downForBuyer BOOLEAN,
	downForMaintenance BOOLEAN,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);