/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.specifications.value.master.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.marketplace.specifications.value.master.model.SpecificationValue;
import com.marketplace.specifications.value.master.service.SpecificationValueLocalService;
import com.marketplace.specifications.value.master.service.SpecificationValueLocalServiceUtil;
import com.marketplace.specifications.value.master.service.persistence.SpecificationValuePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the specification value local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.marketplace.specifications.value.master.service.impl.SpecificationValueLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.marketplace.specifications.value.master.service.impl.SpecificationValueLocalServiceImpl
 * @generated
 */
public abstract class SpecificationValueLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   SpecificationValueLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SpecificationValueLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>SpecificationValueLocalServiceUtil</code>.
	 */

	/**
	 * Adds the specification value to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SpecificationValueLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param specificationValue the specification value
	 * @return the specification value that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SpecificationValue addSpecificationValue(
		SpecificationValue specificationValue) {

		specificationValue.setNew(true);

		return specificationValuePersistence.update(specificationValue);
	}

	/**
	 * Creates a new specification value with the primary key. Does not add the specification value to the database.
	 *
	 * @param specificationValueId the primary key for the new specification value
	 * @return the new specification value
	 */
	@Override
	@Transactional(enabled = false)
	public SpecificationValue createSpecificationValue(
		long specificationValueId) {

		return specificationValuePersistence.create(specificationValueId);
	}

	/**
	 * Deletes the specification value with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SpecificationValueLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param specificationValueId the primary key of the specification value
	 * @return the specification value that was removed
	 * @throws PortalException if a specification value with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SpecificationValue deleteSpecificationValue(
			long specificationValueId)
		throws PortalException {

		return specificationValuePersistence.remove(specificationValueId);
	}

	/**
	 * Deletes the specification value from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SpecificationValueLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param specificationValue the specification value
	 * @return the specification value that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SpecificationValue deleteSpecificationValue(
		SpecificationValue specificationValue) {

		return specificationValuePersistence.remove(specificationValue);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return specificationValuePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			SpecificationValue.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return specificationValuePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.marketplace.specifications.value.master.model.impl.SpecificationValueModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return specificationValuePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.marketplace.specifications.value.master.model.impl.SpecificationValueModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return specificationValuePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return specificationValuePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return specificationValuePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public SpecificationValue fetchSpecificationValue(
		long specificationValueId) {

		return specificationValuePersistence.fetchByPrimaryKey(
			specificationValueId);
	}

	/**
	 * Returns the specification value matching the UUID and group.
	 *
	 * @param uuid the specification value's UUID
	 * @param groupId the primary key of the group
	 * @return the matching specification value, or <code>null</code> if a matching specification value could not be found
	 */
	@Override
	public SpecificationValue fetchSpecificationValueByUuidAndGroupId(
		String uuid, long groupId) {

		return specificationValuePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the specification value with the primary key.
	 *
	 * @param specificationValueId the primary key of the specification value
	 * @return the specification value
	 * @throws PortalException if a specification value with the primary key could not be found
	 */
	@Override
	public SpecificationValue getSpecificationValue(long specificationValueId)
		throws PortalException {

		return specificationValuePersistence.findByPrimaryKey(
			specificationValueId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			specificationValueLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SpecificationValue.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"specificationValueId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			specificationValueLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(SpecificationValue.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"specificationValueId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			specificationValueLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SpecificationValue.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"specificationValueId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<SpecificationValue>() {

				@Override
				public void performAction(SpecificationValue specificationValue)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, specificationValue);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(SpecificationValue.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return specificationValuePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement SpecificationValueLocalServiceImpl#deleteSpecificationValue(SpecificationValue) to avoid orphaned data");
		}

		return specificationValueLocalService.deleteSpecificationValue(
			(SpecificationValue)persistedModel);
	}

	@Override
	public BasePersistence<SpecificationValue> getBasePersistence() {
		return specificationValuePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return specificationValuePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the specification values matching the UUID and company.
	 *
	 * @param uuid the UUID of the specification values
	 * @param companyId the primary key of the company
	 * @return the matching specification values, or an empty list if no matches were found
	 */
	@Override
	public List<SpecificationValue> getSpecificationValuesByUuidAndCompanyId(
		String uuid, long companyId) {

		return specificationValuePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of specification values matching the UUID and company.
	 *
	 * @param uuid the UUID of the specification values
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of specification values
	 * @param end the upper bound of the range of specification values (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching specification values, or an empty list if no matches were found
	 */
	@Override
	public List<SpecificationValue> getSpecificationValuesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<SpecificationValue> orderByComparator) {

		return specificationValuePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the specification value matching the UUID and group.
	 *
	 * @param uuid the specification value's UUID
	 * @param groupId the primary key of the group
	 * @return the matching specification value
	 * @throws PortalException if a matching specification value could not be found
	 */
	@Override
	public SpecificationValue getSpecificationValueByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return specificationValuePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the specification values.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.marketplace.specifications.value.master.model.impl.SpecificationValueModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of specification values
	 * @param end the upper bound of the range of specification values (not inclusive)
	 * @return the range of specification values
	 */
	@Override
	public List<SpecificationValue> getSpecificationValues(int start, int end) {
		return specificationValuePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of specification values.
	 *
	 * @return the number of specification values
	 */
	@Override
	public int getSpecificationValuesCount() {
		return specificationValuePersistence.countAll();
	}

	/**
	 * Updates the specification value in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SpecificationValueLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param specificationValue the specification value
	 * @return the specification value that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SpecificationValue updateSpecificationValue(
		SpecificationValue specificationValue) {

		return specificationValuePersistence.update(specificationValue);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SpecificationValueLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		specificationValueLocalService =
			(SpecificationValueLocalService)aopProxy;

		_setLocalServiceUtilService(specificationValueLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SpecificationValueLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SpecificationValue.class;
	}

	protected String getModelClassName() {
		return SpecificationValue.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				specificationValuePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		SpecificationValueLocalService specificationValueLocalService) {

		try {
			Field field =
				SpecificationValueLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, specificationValueLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected SpecificationValueLocalService specificationValueLocalService;

	@Reference
	protected SpecificationValuePersistence specificationValuePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		SpecificationValueLocalServiceBaseImpl.class);

}