/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.variant.values.master.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.marketplace.variant.values.master.model.VariantValue;
import com.marketplace.variant.values.master.model.VariantValueModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the VariantValue service. Represents a row in the &quot;marketplace_variant_value&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VariantValueModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VariantValueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VariantValueImpl
 * @generated
 */
public class VariantValueModelImpl
	extends BaseModelImpl<VariantValue> implements VariantValueModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a variant value model instance should use the <code>VariantValue</code> interface instead.
	 */
	public static final String TABLE_NAME = "marketplace_variant_value";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"variantValueId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"productVariantId", Types.BIGINT},
		{"variantVal", Types.VARCHAR}, {"draftProductId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"createdBy", Types.BIGINT}, {"modifiedDate", Types.TIMESTAMP},
		{"modifiedBy", Types.BIGINT}, {"ipAddress", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("variantValueId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productVariantId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("variantVal", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("draftProductId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table marketplace_variant_value (uuid_ VARCHAR(75) null,variantValueId LONG not null primary key,groupId LONG,productVariantId LONG,variantVal VARCHAR(75) null,draftProductId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,createdBy LONG,modifiedDate DATE null,modifiedBy LONG,ipAddress VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table marketplace_variant_value";

	public static final String ORDER_BY_JPQL =
		" ORDER BY variantValue.variantValueId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY marketplace_variant_value.variantValueId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DRAFTPRODUCTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRODUCTVARIANTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VARIANTVAL_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VARIANTVALUEID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public VariantValueModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _variantValueId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVariantValueId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _variantValueId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VariantValue.class;
	}

	@Override
	public String getModelClassName() {
		return VariantValue.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<VariantValue, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<VariantValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VariantValue, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((VariantValue)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<VariantValue, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<VariantValue, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(VariantValue)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<VariantValue, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<VariantValue, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<VariantValue, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<VariantValue, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<VariantValue, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<VariantValue, Object>>();
		Map<String, BiConsumer<VariantValue, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<VariantValue, ?>>();

		attributeGetterFunctions.put("uuid", VariantValue::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<VariantValue, String>)VariantValue::setUuid);
		attributeGetterFunctions.put(
			"variantValueId", VariantValue::getVariantValueId);
		attributeSetterBiConsumers.put(
			"variantValueId",
			(BiConsumer<VariantValue, Long>)VariantValue::setVariantValueId);
		attributeGetterFunctions.put("groupId", VariantValue::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<VariantValue, Long>)VariantValue::setGroupId);
		attributeGetterFunctions.put(
			"productVariantId", VariantValue::getProductVariantId);
		attributeSetterBiConsumers.put(
			"productVariantId",
			(BiConsumer<VariantValue, Long>)VariantValue::setProductVariantId);
		attributeGetterFunctions.put("variantVal", VariantValue::getVariantVal);
		attributeSetterBiConsumers.put(
			"variantVal",
			(BiConsumer<VariantValue, String>)VariantValue::setVariantVal);
		attributeGetterFunctions.put(
			"draftProductId", VariantValue::getDraftProductId);
		attributeSetterBiConsumers.put(
			"draftProductId",
			(BiConsumer<VariantValue, Long>)VariantValue::setDraftProductId);
		attributeGetterFunctions.put("companyId", VariantValue::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<VariantValue, Long>)VariantValue::setCompanyId);
		attributeGetterFunctions.put("userId", VariantValue::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<VariantValue, Long>)VariantValue::setUserId);
		attributeGetterFunctions.put("userName", VariantValue::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<VariantValue, String>)VariantValue::setUserName);
		attributeGetterFunctions.put("createDate", VariantValue::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<VariantValue, Date>)VariantValue::setCreateDate);
		attributeGetterFunctions.put("createdBy", VariantValue::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<VariantValue, Long>)VariantValue::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", VariantValue::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<VariantValue, Date>)VariantValue::setModifiedDate);
		attributeGetterFunctions.put("modifiedBy", VariantValue::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<VariantValue, Long>)VariantValue::setModifiedBy);
		attributeGetterFunctions.put("ipAddress", VariantValue::getIpAddress);
		attributeSetterBiConsumers.put(
			"ipAddress",
			(BiConsumer<VariantValue, String>)VariantValue::setIpAddress);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getVariantValueId() {
		return _variantValueId;
	}

	@Override
	public void setVariantValueId(long variantValueId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_variantValueId = variantValueId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getProductVariantId() {
		return _productVariantId;
	}

	@Override
	public void setProductVariantId(long productVariantId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productVariantId = productVariantId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProductVariantId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("productVariantId"));
	}

	@Override
	public String getVariantVal() {
		if (_variantVal == null) {
			return "";
		}
		else {
			return _variantVal;
		}
	}

	@Override
	public void setVariantVal(String variantVal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_variantVal = variantVal;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalVariantVal() {
		return getColumnOriginalValue("variantVal");
	}

	@Override
	public long getDraftProductId() {
		return _draftProductId;
	}

	@Override
	public void setDraftProductId(long draftProductId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_draftProductId = draftProductId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDraftProductId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("draftProductId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ipAddress = ipAddress;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(VariantValue.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), VariantValue.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VariantValue toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, VariantValue>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VariantValueImpl variantValueImpl = new VariantValueImpl();

		variantValueImpl.setUuid(getUuid());
		variantValueImpl.setVariantValueId(getVariantValueId());
		variantValueImpl.setGroupId(getGroupId());
		variantValueImpl.setProductVariantId(getProductVariantId());
		variantValueImpl.setVariantVal(getVariantVal());
		variantValueImpl.setDraftProductId(getDraftProductId());
		variantValueImpl.setCompanyId(getCompanyId());
		variantValueImpl.setUserId(getUserId());
		variantValueImpl.setUserName(getUserName());
		variantValueImpl.setCreateDate(getCreateDate());
		variantValueImpl.setCreatedBy(getCreatedBy());
		variantValueImpl.setModifiedDate(getModifiedDate());
		variantValueImpl.setModifiedBy(getModifiedBy());
		variantValueImpl.setIpAddress(getIpAddress());

		variantValueImpl.resetOriginalValues();

		return variantValueImpl;
	}

	@Override
	public VariantValue cloneWithOriginalValues() {
		VariantValueImpl variantValueImpl = new VariantValueImpl();

		variantValueImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		variantValueImpl.setVariantValueId(
			this.<Long>getColumnOriginalValue("variantValueId"));
		variantValueImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		variantValueImpl.setProductVariantId(
			this.<Long>getColumnOriginalValue("productVariantId"));
		variantValueImpl.setVariantVal(
			this.<String>getColumnOriginalValue("variantVal"));
		variantValueImpl.setDraftProductId(
			this.<Long>getColumnOriginalValue("draftProductId"));
		variantValueImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		variantValueImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		variantValueImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		variantValueImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		variantValueImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		variantValueImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		variantValueImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		variantValueImpl.setIpAddress(
			this.<String>getColumnOriginalValue("ipAddress"));

		return variantValueImpl;
	}

	@Override
	public int compareTo(VariantValue variantValue) {
		long primaryKey = variantValue.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof VariantValue)) {
			return false;
		}

		VariantValue variantValue = (VariantValue)object;

		long primaryKey = variantValue.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<VariantValue> toCacheModel() {
		VariantValueCacheModel variantValueCacheModel =
			new VariantValueCacheModel();

		variantValueCacheModel.uuid = getUuid();

		String uuid = variantValueCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			variantValueCacheModel.uuid = null;
		}

		variantValueCacheModel.variantValueId = getVariantValueId();

		variantValueCacheModel.groupId = getGroupId();

		variantValueCacheModel.productVariantId = getProductVariantId();

		variantValueCacheModel.variantVal = getVariantVal();

		String variantVal = variantValueCacheModel.variantVal;

		if ((variantVal != null) && (variantVal.length() == 0)) {
			variantValueCacheModel.variantVal = null;
		}

		variantValueCacheModel.draftProductId = getDraftProductId();

		variantValueCacheModel.companyId = getCompanyId();

		variantValueCacheModel.userId = getUserId();

		variantValueCacheModel.userName = getUserName();

		String userName = variantValueCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			variantValueCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			variantValueCacheModel.createDate = createDate.getTime();
		}
		else {
			variantValueCacheModel.createDate = Long.MIN_VALUE;
		}

		variantValueCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			variantValueCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			variantValueCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		variantValueCacheModel.modifiedBy = getModifiedBy();

		variantValueCacheModel.ipAddress = getIpAddress();

		String ipAddress = variantValueCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			variantValueCacheModel.ipAddress = null;
		}

		return variantValueCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<VariantValue, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<VariantValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VariantValue, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((VariantValue)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, VariantValue>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					VariantValue.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _variantValueId;
	private long _groupId;
	private long _productVariantId;
	private String _variantVal;
	private long _draftProductId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private String _ipAddress;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<VariantValue, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((VariantValue)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("variantValueId", _variantValueId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("productVariantId", _productVariantId);
		_columnOriginalValues.put("variantVal", _variantVal);
		_columnOriginalValues.put("draftProductId", _draftProductId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("ipAddress", _ipAddress);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("variantValueId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("productVariantId", 8L);

		columnBitmasks.put("variantVal", 16L);

		columnBitmasks.put("draftProductId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("createdBy", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("modifiedBy", 4096L);

		columnBitmasks.put("ipAddress", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private VariantValue _escapedModel;

}