/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.product.pkg.content.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.marketplace.product.pkg.content.model.ProductPackageContent;
import com.marketplace.product.pkg.content.model.ProductPackageContentModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProductPackageContent service. Represents a row in the &quot;marketplace_prod_pkg_content&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProductPackageContentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductPackageContentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductPackageContentImpl
 * @generated
 */
public class ProductPackageContentModelImpl
	extends BaseModelImpl<ProductPackageContent>
	implements ProductPackageContentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product package content model instance should use the <code>ProductPackageContent</code> interface instead.
	 */
	public static final String TABLE_NAME = "marketplace_prod_pkg_content";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"packageContentId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"itemName", Types.VARCHAR},
		{"itemQuantity", Types.VARCHAR}, {"draftProductId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createdBy", Types.BIGINT},
		{"modifiedBy", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"ipAddress", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("packageContentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("itemName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("itemQuantity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("draftProductId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table marketplace_prod_pkg_content (uuid_ VARCHAR(75) null,packageContentId LONG not null primary key,groupId LONG,itemName VARCHAR(75) null,itemQuantity VARCHAR(75) null,draftProductId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createdBy LONG,modifiedBy LONG,createDate DATE null,modifiedDate DATE null,ipAddress VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table marketplace_prod_pkg_content";

	public static final String ORDER_BY_JPQL =
		" ORDER BY productPackageContent.packageContentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY marketplace_prod_pkg_content.packageContentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DRAFTPRODUCTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PACKAGECONTENTID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProductPackageContentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _packageContentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPackageContentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _packageContentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProductPackageContent.class;
	}

	@Override
	public String getModelClassName() {
		return ProductPackageContent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProductPackageContent, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProductPackageContent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductPackageContent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProductPackageContent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProductPackageContent, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProductPackageContent, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProductPackageContent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProductPackageContent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProductPackageContent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ProductPackageContent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProductPackageContent, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProductPackageContent, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProductPackageContent, Object>>();
		Map<String, BiConsumer<ProductPackageContent, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ProductPackageContent, ?>>();

		attributeGetterFunctions.put("uuid", ProductPackageContent::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProductPackageContent, String>)
				ProductPackageContent::setUuid);
		attributeGetterFunctions.put(
			"packageContentId", ProductPackageContent::getPackageContentId);
		attributeSetterBiConsumers.put(
			"packageContentId",
			(BiConsumer<ProductPackageContent, Long>)
				ProductPackageContent::setPackageContentId);
		attributeGetterFunctions.put(
			"groupId", ProductPackageContent::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProductPackageContent, Long>)
				ProductPackageContent::setGroupId);
		attributeGetterFunctions.put(
			"itemName", ProductPackageContent::getItemName);
		attributeSetterBiConsumers.put(
			"itemName",
			(BiConsumer<ProductPackageContent, String>)
				ProductPackageContent::setItemName);
		attributeGetterFunctions.put(
			"itemQuantity", ProductPackageContent::getItemQuantity);
		attributeSetterBiConsumers.put(
			"itemQuantity",
			(BiConsumer<ProductPackageContent, String>)
				ProductPackageContent::setItemQuantity);
		attributeGetterFunctions.put(
			"draftProductId", ProductPackageContent::getDraftProductId);
		attributeSetterBiConsumers.put(
			"draftProductId",
			(BiConsumer<ProductPackageContent, Long>)
				ProductPackageContent::setDraftProductId);
		attributeGetterFunctions.put(
			"companyId", ProductPackageContent::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProductPackageContent, Long>)
				ProductPackageContent::setCompanyId);
		attributeGetterFunctions.put(
			"userId", ProductPackageContent::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ProductPackageContent, Long>)
				ProductPackageContent::setUserId);
		attributeGetterFunctions.put(
			"userName", ProductPackageContent::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ProductPackageContent, String>)
				ProductPackageContent::setUserName);
		attributeGetterFunctions.put(
			"createdBy", ProductPackageContent::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ProductPackageContent, Long>)
				ProductPackageContent::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", ProductPackageContent::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ProductPackageContent, Long>)
				ProductPackageContent::setModifiedBy);
		attributeGetterFunctions.put(
			"createDate", ProductPackageContent::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProductPackageContent, Date>)
				ProductPackageContent::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ProductPackageContent::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProductPackageContent, Date>)
				ProductPackageContent::setModifiedDate);
		attributeGetterFunctions.put(
			"ipAddress", ProductPackageContent::getIpAddress);
		attributeSetterBiConsumers.put(
			"ipAddress",
			(BiConsumer<ProductPackageContent, String>)
				ProductPackageContent::setIpAddress);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getPackageContentId() {
		return _packageContentId;
	}

	@Override
	public void setPackageContentId(long packageContentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_packageContentId = packageContentId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public String getItemName() {
		if (_itemName == null) {
			return "";
		}
		else {
			return _itemName;
		}
	}

	@Override
	public void setItemName(String itemName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_itemName = itemName;
	}

	@Override
	public String getItemQuantity() {
		if (_itemQuantity == null) {
			return "";
		}
		else {
			return _itemQuantity;
		}
	}

	@Override
	public void setItemQuantity(String itemQuantity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_itemQuantity = itemQuantity;
	}

	@Override
	public long getDraftProductId() {
		return _draftProductId;
	}

	@Override
	public void setDraftProductId(long draftProductId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_draftProductId = draftProductId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDraftProductId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("draftProductId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ipAddress = ipAddress;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProductPackageContent.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProductPackageContent.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProductPackageContent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProductPackageContent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProductPackageContentImpl productPackageContentImpl =
			new ProductPackageContentImpl();

		productPackageContentImpl.setUuid(getUuid());
		productPackageContentImpl.setPackageContentId(getPackageContentId());
		productPackageContentImpl.setGroupId(getGroupId());
		productPackageContentImpl.setItemName(getItemName());
		productPackageContentImpl.setItemQuantity(getItemQuantity());
		productPackageContentImpl.setDraftProductId(getDraftProductId());
		productPackageContentImpl.setCompanyId(getCompanyId());
		productPackageContentImpl.setUserId(getUserId());
		productPackageContentImpl.setUserName(getUserName());
		productPackageContentImpl.setCreatedBy(getCreatedBy());
		productPackageContentImpl.setModifiedBy(getModifiedBy());
		productPackageContentImpl.setCreateDate(getCreateDate());
		productPackageContentImpl.setModifiedDate(getModifiedDate());
		productPackageContentImpl.setIpAddress(getIpAddress());

		productPackageContentImpl.resetOriginalValues();

		return productPackageContentImpl;
	}

	@Override
	public ProductPackageContent cloneWithOriginalValues() {
		ProductPackageContentImpl productPackageContentImpl =
			new ProductPackageContentImpl();

		productPackageContentImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		productPackageContentImpl.setPackageContentId(
			this.<Long>getColumnOriginalValue("packageContentId"));
		productPackageContentImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		productPackageContentImpl.setItemName(
			this.<String>getColumnOriginalValue("itemName"));
		productPackageContentImpl.setItemQuantity(
			this.<String>getColumnOriginalValue("itemQuantity"));
		productPackageContentImpl.setDraftProductId(
			this.<Long>getColumnOriginalValue("draftProductId"));
		productPackageContentImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		productPackageContentImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		productPackageContentImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		productPackageContentImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		productPackageContentImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		productPackageContentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		productPackageContentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		productPackageContentImpl.setIpAddress(
			this.<String>getColumnOriginalValue("ipAddress"));

		return productPackageContentImpl;
	}

	@Override
	public int compareTo(ProductPackageContent productPackageContent) {
		long primaryKey = productPackageContent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProductPackageContent)) {
			return false;
		}

		ProductPackageContent productPackageContent =
			(ProductPackageContent)object;

		long primaryKey = productPackageContent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProductPackageContent> toCacheModel() {
		ProductPackageContentCacheModel productPackageContentCacheModel =
			new ProductPackageContentCacheModel();

		productPackageContentCacheModel.uuid = getUuid();

		String uuid = productPackageContentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			productPackageContentCacheModel.uuid = null;
		}

		productPackageContentCacheModel.packageContentId =
			getPackageContentId();

		productPackageContentCacheModel.groupId = getGroupId();

		productPackageContentCacheModel.itemName = getItemName();

		String itemName = productPackageContentCacheModel.itemName;

		if ((itemName != null) && (itemName.length() == 0)) {
			productPackageContentCacheModel.itemName = null;
		}

		productPackageContentCacheModel.itemQuantity = getItemQuantity();

		String itemQuantity = productPackageContentCacheModel.itemQuantity;

		if ((itemQuantity != null) && (itemQuantity.length() == 0)) {
			productPackageContentCacheModel.itemQuantity = null;
		}

		productPackageContentCacheModel.draftProductId = getDraftProductId();

		productPackageContentCacheModel.companyId = getCompanyId();

		productPackageContentCacheModel.userId = getUserId();

		productPackageContentCacheModel.userName = getUserName();

		String userName = productPackageContentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			productPackageContentCacheModel.userName = null;
		}

		productPackageContentCacheModel.createdBy = getCreatedBy();

		productPackageContentCacheModel.modifiedBy = getModifiedBy();

		Date createDate = getCreateDate();

		if (createDate != null) {
			productPackageContentCacheModel.createDate = createDate.getTime();
		}
		else {
			productPackageContentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			productPackageContentCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			productPackageContentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		productPackageContentCacheModel.ipAddress = getIpAddress();

		String ipAddress = productPackageContentCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			productPackageContentCacheModel.ipAddress = null;
		}

		return productPackageContentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProductPackageContent, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProductPackageContent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductPackageContent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProductPackageContent)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProductPackageContent>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProductPackageContent.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _packageContentId;
	private long _groupId;
	private String _itemName;
	private String _itemQuantity;
	private long _draftProductId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private long _createdBy;
	private long _modifiedBy;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _ipAddress;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProductPackageContent, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProductPackageContent)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("packageContentId", _packageContentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("itemName", _itemName);
		_columnOriginalValues.put("itemQuantity", _itemQuantity);
		_columnOriginalValues.put("draftProductId", _draftProductId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("ipAddress", _ipAddress);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("packageContentId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("itemName", 8L);

		columnBitmasks.put("itemQuantity", 16L);

		columnBitmasks.put("draftProductId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createdBy", 512L);

		columnBitmasks.put("modifiedBy", 1024L);

		columnBitmasks.put("createDate", 2048L);

		columnBitmasks.put("modifiedDate", 4096L);

		columnBitmasks.put("ipAddress", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProductPackageContent _escapedModel;

}