/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.product.specifications.master.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductSpecification service. Represents a row in the &quot;marketplace_productspecs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.marketplace.product.specifications.master.model.impl.ProductSpecificationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.marketplace.product.specifications.master.model.impl.ProductSpecificationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductSpecification
 * @generated
 */
@ProviderType
public interface ProductSpecificationModel
	extends BaseModel<ProductSpecification>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product specification model instance should use the {@link ProductSpecification} interface instead.
	 */

	/**
	 * Returns the primary key of this product specification.
	 *
	 * @return the primary key of this product specification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product specification.
	 *
	 * @param primaryKey the primary key of this product specification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product specification.
	 *
	 * @return the uuid of this product specification
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this product specification.
	 *
	 * @param uuid the uuid of this product specification
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the product specification ID of this product specification.
	 *
	 * @return the product specification ID of this product specification
	 */
	public long getProductSpecificationId();

	/**
	 * Sets the product specification ID of this product specification.
	 *
	 * @param productSpecificationId the product specification ID of this product specification
	 */
	public void setProductSpecificationId(long productSpecificationId);

	/**
	 * Returns the group ID of this product specification.
	 *
	 * @return the group ID of this product specification
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this product specification.
	 *
	 * @param groupId the group ID of this product specification
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the specification ID of this product specification.
	 *
	 * @return the specification ID of this product specification
	 */
	public long getSpecificationId();

	/**
	 * Sets the specification ID of this product specification.
	 *
	 * @param specificationId the specification ID of this product specification
	 */
	public void setSpecificationId(long specificationId);

	/**
	 * Returns the specification label of this product specification.
	 *
	 * @return the specification label of this product specification
	 */
	@AutoEscape
	public String getSpecificationLabel();

	/**
	 * Sets the specification label of this product specification.
	 *
	 * @param specificationLabel the specification label of this product specification
	 */
	public void setSpecificationLabel(String specificationLabel);

	/**
	 * Returns the specification field type of this product specification.
	 *
	 * @return the specification field type of this product specification
	 */
	@AutoEscape
	public String getSpecificationFieldType();

	/**
	 * Sets the specification field type of this product specification.
	 *
	 * @param specificationFieldType the specification field type of this product specification
	 */
	public void setSpecificationFieldType(String specificationFieldType);

	/**
	 * Returns the draft product ID of this product specification.
	 *
	 * @return the draft product ID of this product specification
	 */
	public long getDraftProductId();

	/**
	 * Sets the draft product ID of this product specification.
	 *
	 * @param draftProductId the draft product ID of this product specification
	 */
	public void setDraftProductId(long draftProductId);

	/**
	 * Returns the is mandatory of this product specification.
	 *
	 * @return the is mandatory of this product specification
	 */
	public boolean getIsMandatory();

	/**
	 * Returns <code>true</code> if this product specification is is mandatory.
	 *
	 * @return <code>true</code> if this product specification is is mandatory; <code>false</code> otherwise
	 */
	public boolean isIsMandatory();

	/**
	 * Sets whether this product specification is is mandatory.
	 *
	 * @param isMandatory the is mandatory of this product specification
	 */
	public void setIsMandatory(boolean isMandatory);

	/**
	 * Returns the company ID of this product specification.
	 *
	 * @return the company ID of this product specification
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product specification.
	 *
	 * @param companyId the company ID of this product specification
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product specification.
	 *
	 * @return the user ID of this product specification
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this product specification.
	 *
	 * @param userId the user ID of this product specification
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product specification.
	 *
	 * @return the user uuid of this product specification
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this product specification.
	 *
	 * @param userUuid the user uuid of this product specification
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this product specification.
	 *
	 * @return the user name of this product specification
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this product specification.
	 *
	 * @param userName the user name of this product specification
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the created by of this product specification.
	 *
	 * @return the created by of this product specification
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this product specification.
	 *
	 * @param createdBy the created by of this product specification
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this product specification.
	 *
	 * @return the modified by of this product specification
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this product specification.
	 *
	 * @param modifiedBy the modified by of this product specification
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the create date of this product specification.
	 *
	 * @return the create date of this product specification
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product specification.
	 *
	 * @param createDate the create date of this product specification
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product specification.
	 *
	 * @return the modified date of this product specification
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product specification.
	 *
	 * @param modifiedDate the modified date of this product specification
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ip address of this product specification.
	 *
	 * @return the ip address of this product specification
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this product specification.
	 *
	 * @param ipAddress the ip address of this product specification
	 */
	public void setIpAddress(String ipAddress);

	@Override
	public ProductSpecification cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}