/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.product.sku.master.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.math.BigDecimal;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductSKU service. Represents a row in the &quot;marketplace_product_sku&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.marketplace.product.sku.master.model.impl.ProductSKUModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.marketplace.product.sku.master.model.impl.ProductSKUImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductSKU
 * @generated
 */
@ProviderType
public interface ProductSKUModel
	extends BaseModel<ProductSKU>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product sku model instance should use the {@link ProductSKU} interface instead.
	 */

	/**
	 * Returns the primary key of this product sku.
	 *
	 * @return the primary key of this product sku
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product sku.
	 *
	 * @param primaryKey the primary key of this product sku
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product sku.
	 *
	 * @return the uuid of this product sku
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this product sku.
	 *
	 * @param uuid the uuid of this product sku
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the product sku ID of this product sku.
	 *
	 * @return the product sku ID of this product sku
	 */
	public long getProductSKUId();

	/**
	 * Sets the product sku ID of this product sku.
	 *
	 * @param productSKUId the product sku ID of this product sku
	 */
	public void setProductSKUId(long productSKUId);

	/**
	 * Returns the group ID of this product sku.
	 *
	 * @return the group ID of this product sku
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this product sku.
	 *
	 * @param groupId the group ID of this product sku
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the draft product ID of this product sku.
	 *
	 * @return the draft product ID of this product sku
	 */
	public long getDraftProductId();

	/**
	 * Sets the draft product ID of this product sku.
	 *
	 * @param draftProductId the draft product ID of this product sku
	 */
	public void setDraftProductId(long draftProductId);

	/**
	 * Returns the sku ID of this product sku.
	 *
	 * @return the sku ID of this product sku
	 */
	@AutoEscape
	public String getSkuId();

	/**
	 * Sets the sku ID of this product sku.
	 *
	 * @param skuId the sku ID of this product sku
	 */
	public void setSkuId(String skuId);

	/**
	 * Returns the seller sku ID of this product sku.
	 *
	 * @return the seller sku ID of this product sku
	 */
	@AutoEscape
	public String getSellerSkuId();

	/**
	 * Sets the seller sku ID of this product sku.
	 *
	 * @param sellerSkuId the seller sku ID of this product sku
	 */
	public void setSellerSkuId(String sellerSkuId);

	/**
	 * Returns the sku name of this product sku.
	 *
	 * @return the sku name of this product sku
	 */
	@AutoEscape
	public String getSkuName();

	/**
	 * Sets the sku name of this product sku.
	 *
	 * @param skuName the sku name of this product sku
	 */
	public void setSkuName(String skuName);

	/**
	 * Returns the sku creation name of this product sku.
	 *
	 * @return the sku creation name of this product sku
	 */
	@AutoEscape
	public String getSkuCreationName();

	/**
	 * Sets the sku creation name of this product sku.
	 *
	 * @param skuCreationName the sku creation name of this product sku
	 */
	public void setSkuCreationName(String skuCreationName);

	/**
	 * Returns the default sku of this product sku.
	 *
	 * @return the default sku of this product sku
	 */
	@AutoEscape
	public String getDefaultSku();

	/**
	 * Sets the default sku of this product sku.
	 *
	 * @param defaultSku the default sku of this product sku
	 */
	public void setDefaultSku(String defaultSku);

	/**
	 * Returns the base price of this product sku.
	 *
	 * @return the base price of this product sku
	 */
	public BigDecimal getBasePrice();

	/**
	 * Sets the base price of this product sku.
	 *
	 * @param basePrice the base price of this product sku
	 */
	public void setBasePrice(BigDecimal basePrice);

	/**
	 * Returns the offer price of this product sku.
	 *
	 * @return the offer price of this product sku
	 */
	public BigDecimal getOfferPrice();

	/**
	 * Sets the offer price of this product sku.
	 *
	 * @param offerPrice the offer price of this product sku
	 */
	public void setOfferPrice(BigDecimal offerPrice);

	/**
	 * Returns the cost of this product sku.
	 *
	 * @return the cost of this product sku
	 */
	public BigDecimal getCost();

	/**
	 * Sets the cost of this product sku.
	 *
	 * @param cost the cost of this product sku
	 */
	public void setCost(BigDecimal cost);

	/**
	 * Returns the margin of this product sku.
	 *
	 * @return the margin of this product sku
	 */
	public BigDecimal getMargin();

	/**
	 * Sets the margin of this product sku.
	 *
	 * @param margin the margin of this product sku
	 */
	public void setMargin(BigDecimal margin);

	/**
	 * Returns the stock of this product sku.
	 *
	 * @return the stock of this product sku
	 */
	public long getStock();

	/**
	 * Sets the stock of this product sku.
	 *
	 * @param stock the stock of this product sku
	 */
	public void setStock(long stock);

	/**
	 * Returns the uom of this product sku.
	 *
	 * @return the uom of this product sku
	 */
	@AutoEscape
	public String getUom();

	/**
	 * Sets the uom of this product sku.
	 *
	 * @param uom the uom of this product sku
	 */
	public void setUom(String uom);

	/**
	 * Returns the minimum order quantity of this product sku.
	 *
	 * @return the minimum order quantity of this product sku
	 */
	public long getMinimumOrderQuantity();

	/**
	 * Sets the minimum order quantity of this product sku.
	 *
	 * @param minimumOrderQuantity the minimum order quantity of this product sku
	 */
	public void setMinimumOrderQuantity(long minimumOrderQuantity);

	/**
	 * Returns the maximum order quantity of this product sku.
	 *
	 * @return the maximum order quantity of this product sku
	 */
	public long getMaximumOrderQuantity();

	/**
	 * Sets the maximum order quantity of this product sku.
	 *
	 * @param maximumOrderQuantity the maximum order quantity of this product sku
	 */
	public void setMaximumOrderQuantity(long maximumOrderQuantity);

	/**
	 * Returns the low stock threshold of this product sku.
	 *
	 * @return the low stock threshold of this product sku
	 */
	public long getLowStockThreshold();

	/**
	 * Sets the low stock threshold of this product sku.
	 *
	 * @param lowStockThreshold the low stock threshold of this product sku
	 */
	public void setLowStockThreshold(long lowStockThreshold);

	/**
	 * Returns the tax of this product sku.
	 *
	 * @return the tax of this product sku
	 */
	@AutoEscape
	public String getTax();

	/**
	 * Sets the tax of this product sku.
	 *
	 * @param tax the tax of this product sku
	 */
	public void setTax(String tax);

	/**
	 * Returns the sku publishing date of this product sku.
	 *
	 * @return the sku publishing date of this product sku
	 */
	public Date getSkuPublishingDate();

	/**
	 * Sets the sku publishing date of this product sku.
	 *
	 * @param skuPublishingDate the sku publishing date of this product sku
	 */
	public void setSkuPublishingDate(Date skuPublishingDate);

	/**
	 * Returns the sku expiry date of this product sku.
	 *
	 * @return the sku expiry date of this product sku
	 */
	public Date getSkuExpiryDate();

	/**
	 * Sets the sku expiry date of this product sku.
	 *
	 * @param skuExpiryDate the sku expiry date of this product sku
	 */
	public void setSkuExpiryDate(Date skuExpiryDate);

	/**
	 * Returns the images of this product sku.
	 *
	 * @return the images of this product sku
	 */
	@AutoEscape
	public String getImages();

	/**
	 * Sets the images of this product sku.
	 *
	 * @param images the images of this product sku
	 */
	public void setImages(String images);

	/**
	 * Returns the company ID of this product sku.
	 *
	 * @return the company ID of this product sku
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product sku.
	 *
	 * @param companyId the company ID of this product sku
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product sku.
	 *
	 * @return the user ID of this product sku
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this product sku.
	 *
	 * @param userId the user ID of this product sku
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product sku.
	 *
	 * @return the user uuid of this product sku
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this product sku.
	 *
	 * @param userUuid the user uuid of this product sku
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this product sku.
	 *
	 * @return the user name of this product sku
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this product sku.
	 *
	 * @param userName the user name of this product sku
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this product sku.
	 *
	 * @return the create date of this product sku
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product sku.
	 *
	 * @param createDate the create date of this product sku
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this product sku.
	 *
	 * @return the created by of this product sku
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this product sku.
	 *
	 * @param createdBy the created by of this product sku
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this product sku.
	 *
	 * @return the modified date of this product sku
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product sku.
	 *
	 * @param modifiedDate the modified date of this product sku
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this product sku.
	 *
	 * @return the modified by of this product sku
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this product sku.
	 *
	 * @param modifiedBy the modified by of this product sku
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the ip address of this product sku.
	 *
	 * @return the ip address of this product sku
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this product sku.
	 *
	 * @param ipAddress the ip address of this product sku
	 */
	public void setIpAddress(String ipAddress);

	@Override
	public ProductSKU cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}