/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.specifications.value.master.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.marketplace.specifications.value.master.model.SpecificationValue;
import com.marketplace.specifications.value.master.model.SpecificationValueModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SpecificationValue service. Represents a row in the &quot;marketplace_specificationvalue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SpecificationValueModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SpecificationValueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SpecificationValueImpl
 * @generated
 */
public class SpecificationValueModelImpl
	extends BaseModelImpl<SpecificationValue>
	implements SpecificationValueModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a specification value model instance should use the <code>SpecificationValue</code> interface instead.
	 */
	public static final String TABLE_NAME = "marketplace_specificationvalue";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"specificationValueId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"specificationId", Types.BIGINT},
		{"specificationValueLabel", Types.VARCHAR},
		{"specificationUOM", Types.VARCHAR}, {"ipAddress", Types.VARCHAR},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"createdBy", Types.BIGINT},
		{"modifiedBy", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("specificationValueId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("specificationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("specificationValueLabel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("specificationUOM", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table marketplace_specificationvalue (uuid_ VARCHAR(75) null,specificationValueId LONG not null primary key,groupId LONG,specificationId LONG,specificationValueLabel VARCHAR(75) null,specificationUOM VARCHAR(75) null,ipAddress VARCHAR(75) null,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,createdBy LONG,modifiedBy LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table marketplace_specificationvalue";

	public static final String ORDER_BY_JPQL =
		" ORDER BY specificationValue.specificationValueId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY marketplace_specificationvalue.specificationValueId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SPECIFICATIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SPECIFICATIONVALUEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SpecificationValueModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _specificationValueId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSpecificationValueId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _specificationValueId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SpecificationValue.class;
	}

	@Override
	public String getModelClassName() {
		return SpecificationValue.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SpecificationValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SpecificationValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SpecificationValue, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SpecificationValue)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SpecificationValue, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SpecificationValue, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SpecificationValue)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SpecificationValue, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SpecificationValue, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SpecificationValue, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SpecificationValue, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SpecificationValue, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SpecificationValue, Object>>();
		Map<String, BiConsumer<SpecificationValue, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SpecificationValue, ?>>();

		attributeGetterFunctions.put("uuid", SpecificationValue::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<SpecificationValue, String>)
				SpecificationValue::setUuid);
		attributeGetterFunctions.put(
			"specificationValueId",
			SpecificationValue::getSpecificationValueId);
		attributeSetterBiConsumers.put(
			"specificationValueId",
			(BiConsumer<SpecificationValue, Long>)
				SpecificationValue::setSpecificationValueId);
		attributeGetterFunctions.put("groupId", SpecificationValue::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SpecificationValue, Long>)
				SpecificationValue::setGroupId);
		attributeGetterFunctions.put(
			"specificationId", SpecificationValue::getSpecificationId);
		attributeSetterBiConsumers.put(
			"specificationId",
			(BiConsumer<SpecificationValue, Long>)
				SpecificationValue::setSpecificationId);
		attributeGetterFunctions.put(
			"specificationValueLabel",
			SpecificationValue::getSpecificationValueLabel);
		attributeSetterBiConsumers.put(
			"specificationValueLabel",
			(BiConsumer<SpecificationValue, String>)
				SpecificationValue::setSpecificationValueLabel);
		attributeGetterFunctions.put(
			"specificationUOM", SpecificationValue::getSpecificationUOM);
		attributeSetterBiConsumers.put(
			"specificationUOM",
			(BiConsumer<SpecificationValue, String>)
				SpecificationValue::setSpecificationUOM);
		attributeGetterFunctions.put(
			"ipAddress", SpecificationValue::getIpAddress);
		attributeSetterBiConsumers.put(
			"ipAddress",
			(BiConsumer<SpecificationValue, String>)
				SpecificationValue::setIpAddress);
		attributeGetterFunctions.put(
			"companyId", SpecificationValue::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SpecificationValue, Long>)
				SpecificationValue::setCompanyId);
		attributeGetterFunctions.put("userId", SpecificationValue::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SpecificationValue, Long>)
				SpecificationValue::setUserId);
		attributeGetterFunctions.put(
			"userName", SpecificationValue::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SpecificationValue, String>)
				SpecificationValue::setUserName);
		attributeGetterFunctions.put(
			"createDate", SpecificationValue::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SpecificationValue, Date>)
				SpecificationValue::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SpecificationValue::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SpecificationValue, Date>)
				SpecificationValue::setModifiedDate);
		attributeGetterFunctions.put(
			"createdBy", SpecificationValue::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<SpecificationValue, Long>)
				SpecificationValue::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", SpecificationValue::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<SpecificationValue, Long>)
				SpecificationValue::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getSpecificationValueId() {
		return _specificationValueId;
	}

	@Override
	public void setSpecificationValueId(long specificationValueId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specificationValueId = specificationValueId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getSpecificationId() {
		return _specificationId;
	}

	@Override
	public void setSpecificationId(long specificationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specificationId = specificationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSpecificationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("specificationId"));
	}

	@Override
	public String getSpecificationValueLabel() {
		if (_specificationValueLabel == null) {
			return "";
		}
		else {
			return _specificationValueLabel;
		}
	}

	@Override
	public void setSpecificationValueLabel(String specificationValueLabel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specificationValueLabel = specificationValueLabel;
	}

	@Override
	public String getSpecificationUOM() {
		if (_specificationUOM == null) {
			return "";
		}
		else {
			return _specificationUOM;
		}
	}

	@Override
	public void setSpecificationUOM(String specificationUOM) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specificationUOM = specificationUOM;
	}

	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ipAddress = ipAddress;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(SpecificationValue.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SpecificationValue.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SpecificationValue toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SpecificationValue>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SpecificationValueImpl specificationValueImpl =
			new SpecificationValueImpl();

		specificationValueImpl.setUuid(getUuid());
		specificationValueImpl.setSpecificationValueId(
			getSpecificationValueId());
		specificationValueImpl.setGroupId(getGroupId());
		specificationValueImpl.setSpecificationId(getSpecificationId());
		specificationValueImpl.setSpecificationValueLabel(
			getSpecificationValueLabel());
		specificationValueImpl.setSpecificationUOM(getSpecificationUOM());
		specificationValueImpl.setIpAddress(getIpAddress());
		specificationValueImpl.setCompanyId(getCompanyId());
		specificationValueImpl.setUserId(getUserId());
		specificationValueImpl.setUserName(getUserName());
		specificationValueImpl.setCreateDate(getCreateDate());
		specificationValueImpl.setModifiedDate(getModifiedDate());
		specificationValueImpl.setCreatedBy(getCreatedBy());
		specificationValueImpl.setModifiedBy(getModifiedBy());

		specificationValueImpl.resetOriginalValues();

		return specificationValueImpl;
	}

	@Override
	public SpecificationValue cloneWithOriginalValues() {
		SpecificationValueImpl specificationValueImpl =
			new SpecificationValueImpl();

		specificationValueImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		specificationValueImpl.setSpecificationValueId(
			this.<Long>getColumnOriginalValue("specificationValueId"));
		specificationValueImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		specificationValueImpl.setSpecificationId(
			this.<Long>getColumnOriginalValue("specificationId"));
		specificationValueImpl.setSpecificationValueLabel(
			this.<String>getColumnOriginalValue("specificationValueLabel"));
		specificationValueImpl.setSpecificationUOM(
			this.<String>getColumnOriginalValue("specificationUOM"));
		specificationValueImpl.setIpAddress(
			this.<String>getColumnOriginalValue("ipAddress"));
		specificationValueImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		specificationValueImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		specificationValueImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		specificationValueImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		specificationValueImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		specificationValueImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		specificationValueImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));

		return specificationValueImpl;
	}

	@Override
	public int compareTo(SpecificationValue specificationValue) {
		long primaryKey = specificationValue.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SpecificationValue)) {
			return false;
		}

		SpecificationValue specificationValue = (SpecificationValue)object;

		long primaryKey = specificationValue.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SpecificationValue> toCacheModel() {
		SpecificationValueCacheModel specificationValueCacheModel =
			new SpecificationValueCacheModel();

		specificationValueCacheModel.uuid = getUuid();

		String uuid = specificationValueCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			specificationValueCacheModel.uuid = null;
		}

		specificationValueCacheModel.specificationValueId =
			getSpecificationValueId();

		specificationValueCacheModel.groupId = getGroupId();

		specificationValueCacheModel.specificationId = getSpecificationId();

		specificationValueCacheModel.specificationValueLabel =
			getSpecificationValueLabel();

		String specificationValueLabel =
			specificationValueCacheModel.specificationValueLabel;

		if ((specificationValueLabel != null) &&
			(specificationValueLabel.length() == 0)) {

			specificationValueCacheModel.specificationValueLabel = null;
		}

		specificationValueCacheModel.specificationUOM = getSpecificationUOM();

		String specificationUOM = specificationValueCacheModel.specificationUOM;

		if ((specificationUOM != null) && (specificationUOM.length() == 0)) {
			specificationValueCacheModel.specificationUOM = null;
		}

		specificationValueCacheModel.ipAddress = getIpAddress();

		String ipAddress = specificationValueCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			specificationValueCacheModel.ipAddress = null;
		}

		specificationValueCacheModel.companyId = getCompanyId();

		specificationValueCacheModel.userId = getUserId();

		specificationValueCacheModel.userName = getUserName();

		String userName = specificationValueCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			specificationValueCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			specificationValueCacheModel.createDate = createDate.getTime();
		}
		else {
			specificationValueCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			specificationValueCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			specificationValueCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		specificationValueCacheModel.createdBy = getCreatedBy();

		specificationValueCacheModel.modifiedBy = getModifiedBy();

		return specificationValueCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SpecificationValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SpecificationValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SpecificationValue, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SpecificationValue)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SpecificationValue>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SpecificationValue.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _specificationValueId;
	private long _groupId;
	private long _specificationId;
	private String _specificationValueLabel;
	private String _specificationUOM;
	private String _ipAddress;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdBy;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SpecificationValue, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SpecificationValue)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"specificationValueId", _specificationValueId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("specificationId", _specificationId);
		_columnOriginalValues.put(
			"specificationValueLabel", _specificationValueLabel);
		_columnOriginalValues.put("specificationUOM", _specificationUOM);
		_columnOriginalValues.put("ipAddress", _ipAddress);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("specificationValueId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("specificationId", 8L);

		columnBitmasks.put("specificationValueLabel", 16L);

		columnBitmasks.put("specificationUOM", 32L);

		columnBitmasks.put("ipAddress", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("createdBy", 4096L);

		columnBitmasks.put("modifiedBy", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SpecificationValue _escapedModel;

}