/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.category.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.marketplace.category.model.Category;
import com.marketplace.category.model.CategoryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Category service. Represents a row in the &quot;marketplace_category&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CategoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CategoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CategoryImpl
 * @generated
 */
@JSON(strict = true)
public class CategoryModelImpl
	extends BaseModelImpl<Category> implements CategoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a category model instance should use the <code>Category</code> interface instead.
	 */
	public static final String TABLE_NAME = "marketplace_category";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"categoryId", Types.BIGINT},
		{"parentCategoryId", Types.BIGINT}, {"assetCategoryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"categoryName", Types.VARCHAR},
		{"categoryCode", Types.VARCHAR}, {"categoryDescription", Types.VARCHAR},
		{"categoryType", Types.VARCHAR}, {"assignManager", Types.BIGINT},
		{"assignReviewer", Types.BIGINT},
		{"categoryApprovalStatus", Types.VARCHAR},
		{"reviewerRemarks", Types.VARCHAR},
		{"categoryExpiryDate", Types.TIMESTAMP},
		{"categoryInactive", Types.BOOLEAN},
		{"externalReferenceId", Types.VARCHAR},
		{"categoryImageId", Types.BIGINT}, {"categoryImageURL", Types.VARCHAR},
		{"managerRemarks", Types.VARCHAR}, {"treePath", Types.VARCHAR},
		{"termsCondition", Types.VARCHAR}, {"hasChild", Types.BOOLEAN},
		{"customAtr1", Types.VARCHAR}, {"customAtr2", Types.VARCHAR},
		{"customAtr3", Types.VARCHAR}, {"customAtr4", Types.VARCHAR},
		{"customAtr5", Types.VARCHAR}, {"customAtr6", Types.VARCHAR},
		{"customAtr7", Types.VARCHAR}, {"customAtr8", Types.VARCHAR},
		{"customAtr9", Types.VARCHAR}, {"customAtr10", Types.VARCHAR},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"ipAddress", Types.VARCHAR}, {"isActive", Types.BOOLEAN},
		{"downForSeller", Types.BOOLEAN}, {"downForBuyer", Types.BOOLEAN},
		{"downForMaintenance", Types.BOOLEAN}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("categoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentCategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetCategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoryName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("categoryCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("categoryDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("categoryType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assignManager", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assignReviewer", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoryApprovalStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reviewerRemarks", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("categoryExpiryDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("categoryInactive", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("externalReferenceId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("categoryImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoryImageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("managerRemarks", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("treePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("termsCondition", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hasChild", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("customAtr1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customAtr2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customAtr3", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customAtr4", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customAtr5", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customAtr6", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customAtr7", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customAtr8", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customAtr9", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customAtr10", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isActive", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("downForSeller", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("downForBuyer", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("downForMaintenance", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table marketplace_category (uuid_ VARCHAR(75) null,categoryId LONG not null primary key,parentCategoryId LONG,assetCategoryId LONG,groupId LONG,categoryName VARCHAR(75) null,categoryCode VARCHAR(75) null,categoryDescription VARCHAR(75) null,categoryType VARCHAR(75) null,assignManager LONG,assignReviewer LONG,categoryApprovalStatus VARCHAR(75) null,reviewerRemarks VARCHAR(75) null,categoryExpiryDate DATE null,categoryInactive BOOLEAN,externalReferenceId VARCHAR(75) null,categoryImageId LONG,categoryImageURL VARCHAR(75) null,managerRemarks VARCHAR(75) null,treePath VARCHAR(75) null,termsCondition VARCHAR(75) null,hasChild BOOLEAN,customAtr1 VARCHAR(75) null,customAtr2 VARCHAR(75) null,customAtr3 VARCHAR(75) null,customAtr4 VARCHAR(75) null,customAtr5 VARCHAR(75) null,customAtr6 VARCHAR(75) null,customAtr7 VARCHAR(75) null,customAtr8 VARCHAR(75) null,customAtr9 VARCHAR(75) null,customAtr10 VARCHAR(75) null,createdBy LONG,modifiedBy LONG,ipAddress VARCHAR(75) null,isActive BOOLEAN,downForSeller BOOLEAN,downForBuyer BOOLEAN,downForMaintenance BOOLEAN,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table marketplace_category";

	public static final String ORDER_BY_JPQL =
		" ORDER BY category.categoryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY marketplace_category.categoryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSETCATEGORYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSIGNMANAGER_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSIGNREVIEWER_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CATEGORYAPPROVALSTATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDBY_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTCATEGORYID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CATEGORYID_COLUMN_BITMASK = 512L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CategoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _categoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCategoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _categoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Category.class;
	}

	@Override
	public String getModelClassName() {
		return Category.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Category, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Category, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Category, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Category)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Category, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Category, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Category)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Category, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Category, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Category, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Category, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Category, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Category, Object>>();
		Map<String, BiConsumer<Category, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Category, ?>>();

		attributeGetterFunctions.put("uuid", Category::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Category, String>)Category::setUuid);
		attributeGetterFunctions.put("categoryId", Category::getCategoryId);
		attributeSetterBiConsumers.put(
			"categoryId", (BiConsumer<Category, Long>)Category::setCategoryId);
		attributeGetterFunctions.put(
			"parentCategoryId", Category::getParentCategoryId);
		attributeSetterBiConsumers.put(
			"parentCategoryId",
			(BiConsumer<Category, Long>)Category::setParentCategoryId);
		attributeGetterFunctions.put(
			"assetCategoryId", Category::getAssetCategoryId);
		attributeSetterBiConsumers.put(
			"assetCategoryId",
			(BiConsumer<Category, Long>)Category::setAssetCategoryId);
		attributeGetterFunctions.put("groupId", Category::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Category, Long>)Category::setGroupId);
		attributeGetterFunctions.put("categoryName", Category::getCategoryName);
		attributeSetterBiConsumers.put(
			"categoryName",
			(BiConsumer<Category, String>)Category::setCategoryName);
		attributeGetterFunctions.put("categoryCode", Category::getCategoryCode);
		attributeSetterBiConsumers.put(
			"categoryCode",
			(BiConsumer<Category, String>)Category::setCategoryCode);
		attributeGetterFunctions.put(
			"categoryDescription", Category::getCategoryDescription);
		attributeSetterBiConsumers.put(
			"categoryDescription",
			(BiConsumer<Category, String>)Category::setCategoryDescription);
		attributeGetterFunctions.put("categoryType", Category::getCategoryType);
		attributeSetterBiConsumers.put(
			"categoryType",
			(BiConsumer<Category, String>)Category::setCategoryType);
		attributeGetterFunctions.put(
			"assignManager", Category::getAssignManager);
		attributeSetterBiConsumers.put(
			"assignManager",
			(BiConsumer<Category, Long>)Category::setAssignManager);
		attributeGetterFunctions.put(
			"assignReviewer", Category::getAssignReviewer);
		attributeSetterBiConsumers.put(
			"assignReviewer",
			(BiConsumer<Category, Long>)Category::setAssignReviewer);
		attributeGetterFunctions.put(
			"categoryApprovalStatus", Category::getCategoryApprovalStatus);
		attributeSetterBiConsumers.put(
			"categoryApprovalStatus",
			(BiConsumer<Category, String>)Category::setCategoryApprovalStatus);
		attributeGetterFunctions.put(
			"reviewerRemarks", Category::getReviewerRemarks);
		attributeSetterBiConsumers.put(
			"reviewerRemarks",
			(BiConsumer<Category, String>)Category::setReviewerRemarks);
		attributeGetterFunctions.put(
			"categoryExpiryDate", Category::getCategoryExpiryDate);
		attributeSetterBiConsumers.put(
			"categoryExpiryDate",
			(BiConsumer<Category, Date>)Category::setCategoryExpiryDate);
		attributeGetterFunctions.put(
			"categoryInactive", Category::getCategoryInactive);
		attributeSetterBiConsumers.put(
			"categoryInactive",
			(BiConsumer<Category, Boolean>)Category::setCategoryInactive);
		attributeGetterFunctions.put(
			"externalReferenceId", Category::getExternalReferenceId);
		attributeSetterBiConsumers.put(
			"externalReferenceId",
			(BiConsumer<Category, String>)Category::setExternalReferenceId);
		attributeGetterFunctions.put(
			"categoryImageId", Category::getCategoryImageId);
		attributeSetterBiConsumers.put(
			"categoryImageId",
			(BiConsumer<Category, Long>)Category::setCategoryImageId);
		attributeGetterFunctions.put(
			"categoryImageURL", Category::getCategoryImageURL);
		attributeSetterBiConsumers.put(
			"categoryImageURL",
			(BiConsumer<Category, String>)Category::setCategoryImageURL);
		attributeGetterFunctions.put(
			"managerRemarks", Category::getManagerRemarks);
		attributeSetterBiConsumers.put(
			"managerRemarks",
			(BiConsumer<Category, String>)Category::setManagerRemarks);
		attributeGetterFunctions.put("treePath", Category::getTreePath);
		attributeSetterBiConsumers.put(
			"treePath", (BiConsumer<Category, String>)Category::setTreePath);
		attributeGetterFunctions.put(
			"termsCondition", Category::getTermsCondition);
		attributeSetterBiConsumers.put(
			"termsCondition",
			(BiConsumer<Category, String>)Category::setTermsCondition);
		attributeGetterFunctions.put("hasChild", Category::getHasChild);
		attributeSetterBiConsumers.put(
			"hasChild", (BiConsumer<Category, Boolean>)Category::setHasChild);
		attributeGetterFunctions.put("customAtr1", Category::getCustomAtr1);
		attributeSetterBiConsumers.put(
			"customAtr1",
			(BiConsumer<Category, String>)Category::setCustomAtr1);
		attributeGetterFunctions.put("customAtr2", Category::getCustomAtr2);
		attributeSetterBiConsumers.put(
			"customAtr2",
			(BiConsumer<Category, String>)Category::setCustomAtr2);
		attributeGetterFunctions.put("customAtr3", Category::getCustomAtr3);
		attributeSetterBiConsumers.put(
			"customAtr3",
			(BiConsumer<Category, String>)Category::setCustomAtr3);
		attributeGetterFunctions.put("customAtr4", Category::getCustomAtr4);
		attributeSetterBiConsumers.put(
			"customAtr4",
			(BiConsumer<Category, String>)Category::setCustomAtr4);
		attributeGetterFunctions.put("customAtr5", Category::getCustomAtr5);
		attributeSetterBiConsumers.put(
			"customAtr5",
			(BiConsumer<Category, String>)Category::setCustomAtr5);
		attributeGetterFunctions.put("customAtr6", Category::getCustomAtr6);
		attributeSetterBiConsumers.put(
			"customAtr6",
			(BiConsumer<Category, String>)Category::setCustomAtr6);
		attributeGetterFunctions.put("customAtr7", Category::getCustomAtr7);
		attributeSetterBiConsumers.put(
			"customAtr7",
			(BiConsumer<Category, String>)Category::setCustomAtr7);
		attributeGetterFunctions.put("customAtr8", Category::getCustomAtr8);
		attributeSetterBiConsumers.put(
			"customAtr8",
			(BiConsumer<Category, String>)Category::setCustomAtr8);
		attributeGetterFunctions.put("customAtr9", Category::getCustomAtr9);
		attributeSetterBiConsumers.put(
			"customAtr9",
			(BiConsumer<Category, String>)Category::setCustomAtr9);
		attributeGetterFunctions.put("customAtr10", Category::getCustomAtr10);
		attributeSetterBiConsumers.put(
			"customAtr10",
			(BiConsumer<Category, String>)Category::setCustomAtr10);
		attributeGetterFunctions.put("createdBy", Category::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy", (BiConsumer<Category, Long>)Category::setCreatedBy);
		attributeGetterFunctions.put("modifiedBy", Category::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy", (BiConsumer<Category, Long>)Category::setModifiedBy);
		attributeGetterFunctions.put("ipAddress", Category::getIpAddress);
		attributeSetterBiConsumers.put(
			"ipAddress", (BiConsumer<Category, String>)Category::setIpAddress);
		attributeGetterFunctions.put("isActive", Category::getIsActive);
		attributeSetterBiConsumers.put(
			"isActive", (BiConsumer<Category, Boolean>)Category::setIsActive);
		attributeGetterFunctions.put(
			"downForSeller", Category::getDownForSeller);
		attributeSetterBiConsumers.put(
			"downForSeller",
			(BiConsumer<Category, Boolean>)Category::setDownForSeller);
		attributeGetterFunctions.put("downForBuyer", Category::getDownForBuyer);
		attributeSetterBiConsumers.put(
			"downForBuyer",
			(BiConsumer<Category, Boolean>)Category::setDownForBuyer);
		attributeGetterFunctions.put(
			"downForMaintenance", Category::getDownForMaintenance);
		attributeSetterBiConsumers.put(
			"downForMaintenance",
			(BiConsumer<Category, Boolean>)Category::setDownForMaintenance);
		attributeGetterFunctions.put("companyId", Category::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Category, Long>)Category::setCompanyId);
		attributeGetterFunctions.put("userId", Category::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Category, Long>)Category::setUserId);
		attributeGetterFunctions.put("userName", Category::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Category, String>)Category::setUserName);
		attributeGetterFunctions.put("createDate", Category::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Category, Date>)Category::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Category::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Category, Date>)Category::setModifiedDate);
		attributeGetterFunctions.put("status", Category::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Category, Integer>)Category::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Category::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Category, Long>)Category::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Category::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Category, String>)Category::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Category::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Category, Date>)Category::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryId = categoryId;
	}

	@JSON
	@Override
	public long getParentCategoryId() {
		return _parentCategoryId;
	}

	@Override
	public void setParentCategoryId(long parentCategoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentCategoryId = parentCategoryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentCategoryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentCategoryId"));
	}

	@JSON
	@Override
	public long getAssetCategoryId() {
		return _assetCategoryId;
	}

	@Override
	public void setAssetCategoryId(long assetCategoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetCategoryId = assetCategoryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAssetCategoryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("assetCategoryId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public String getCategoryName() {
		if (_categoryName == null) {
			return "";
		}
		else {
			return _categoryName;
		}
	}

	@Override
	public void setCategoryName(String categoryName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryName = categoryName;
	}

	@JSON
	@Override
	public String getCategoryCode() {
		if (_categoryCode == null) {
			return "";
		}
		else {
			return _categoryCode;
		}
	}

	@Override
	public void setCategoryCode(String categoryCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryCode = categoryCode;
	}

	@JSON
	@Override
	public String getCategoryDescription() {
		if (_categoryDescription == null) {
			return "";
		}
		else {
			return _categoryDescription;
		}
	}

	@Override
	public void setCategoryDescription(String categoryDescription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryDescription = categoryDescription;
	}

	@JSON
	@Override
	public String getCategoryType() {
		if (_categoryType == null) {
			return "";
		}
		else {
			return _categoryType;
		}
	}

	@Override
	public void setCategoryType(String categoryType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryType = categoryType;
	}

	@JSON
	@Override
	public long getAssignManager() {
		return _assignManager;
	}

	@Override
	public void setAssignManager(long assignManager) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assignManager = assignManager;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAssignManager() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("assignManager"));
	}

	@JSON
	@Override
	public long getAssignReviewer() {
		return _assignReviewer;
	}

	@Override
	public void setAssignReviewer(long assignReviewer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assignReviewer = assignReviewer;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAssignReviewer() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("assignReviewer"));
	}

	@JSON
	@Override
	public String getCategoryApprovalStatus() {
		if (_categoryApprovalStatus == null) {
			return "";
		}
		else {
			return _categoryApprovalStatus;
		}
	}

	@Override
	public void setCategoryApprovalStatus(String categoryApprovalStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryApprovalStatus = categoryApprovalStatus;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCategoryApprovalStatus() {
		return getColumnOriginalValue("categoryApprovalStatus");
	}

	@JSON
	@Override
	public String getReviewerRemarks() {
		if (_reviewerRemarks == null) {
			return "";
		}
		else {
			return _reviewerRemarks;
		}
	}

	@Override
	public void setReviewerRemarks(String reviewerRemarks) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reviewerRemarks = reviewerRemarks;
	}

	@JSON
	@Override
	public Date getCategoryExpiryDate() {
		return _categoryExpiryDate;
	}

	@Override
	public void setCategoryExpiryDate(Date categoryExpiryDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryExpiryDate = categoryExpiryDate;
	}

	@JSON
	@Override
	public Boolean getCategoryInactive() {
		return _categoryInactive;
	}

	@Override
	public void setCategoryInactive(Boolean categoryInactive) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryInactive = categoryInactive;
	}

	@JSON
	@Override
	public String getExternalReferenceId() {
		if (_externalReferenceId == null) {
			return "";
		}
		else {
			return _externalReferenceId;
		}
	}

	@Override
	public void setExternalReferenceId(String externalReferenceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceId = externalReferenceId;
	}

	@JSON
	@Override
	public long getCategoryImageId() {
		return _categoryImageId;
	}

	@Override
	public void setCategoryImageId(long categoryImageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryImageId = categoryImageId;
	}

	@JSON
	@Override
	public String getCategoryImageURL() {
		if (_categoryImageURL == null) {
			return "";
		}
		else {
			return _categoryImageURL;
		}
	}

	@Override
	public void setCategoryImageURL(String categoryImageURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryImageURL = categoryImageURL;
	}

	@JSON
	@Override
	public String getManagerRemarks() {
		if (_managerRemarks == null) {
			return "";
		}
		else {
			return _managerRemarks;
		}
	}

	@Override
	public void setManagerRemarks(String managerRemarks) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_managerRemarks = managerRemarks;
	}

	@JSON
	@Override
	public String getTreePath() {
		if (_treePath == null) {
			return "";
		}
		else {
			return _treePath;
		}
	}

	@Override
	public void setTreePath(String treePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_treePath = treePath;
	}

	@JSON
	@Override
	public String getTermsCondition() {
		if (_termsCondition == null) {
			return "";
		}
		else {
			return _termsCondition;
		}
	}

	@Override
	public void setTermsCondition(String termsCondition) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_termsCondition = termsCondition;
	}

	@JSON
	@Override
	public Boolean getHasChild() {
		return _hasChild;
	}

	@Override
	public void setHasChild(Boolean hasChild) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hasChild = hasChild;
	}

	@JSON
	@Override
	public String getCustomAtr1() {
		if (_customAtr1 == null) {
			return "";
		}
		else {
			return _customAtr1;
		}
	}

	@Override
	public void setCustomAtr1(String customAtr1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr1 = customAtr1;
	}

	@JSON
	@Override
	public String getCustomAtr2() {
		if (_customAtr2 == null) {
			return "";
		}
		else {
			return _customAtr2;
		}
	}

	@Override
	public void setCustomAtr2(String customAtr2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr2 = customAtr2;
	}

	@JSON
	@Override
	public String getCustomAtr3() {
		if (_customAtr3 == null) {
			return "";
		}
		else {
			return _customAtr3;
		}
	}

	@Override
	public void setCustomAtr3(String customAtr3) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr3 = customAtr3;
	}

	@JSON
	@Override
	public String getCustomAtr4() {
		if (_customAtr4 == null) {
			return "";
		}
		else {
			return _customAtr4;
		}
	}

	@Override
	public void setCustomAtr4(String customAtr4) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr4 = customAtr4;
	}

	@JSON
	@Override
	public String getCustomAtr5() {
		if (_customAtr5 == null) {
			return "";
		}
		else {
			return _customAtr5;
		}
	}

	@Override
	public void setCustomAtr5(String customAtr5) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr5 = customAtr5;
	}

	@JSON
	@Override
	public String getCustomAtr6() {
		if (_customAtr6 == null) {
			return "";
		}
		else {
			return _customAtr6;
		}
	}

	@Override
	public void setCustomAtr6(String customAtr6) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr6 = customAtr6;
	}

	@JSON
	@Override
	public String getCustomAtr7() {
		if (_customAtr7 == null) {
			return "";
		}
		else {
			return _customAtr7;
		}
	}

	@Override
	public void setCustomAtr7(String customAtr7) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr7 = customAtr7;
	}

	@JSON
	@Override
	public String getCustomAtr8() {
		if (_customAtr8 == null) {
			return "";
		}
		else {
			return _customAtr8;
		}
	}

	@Override
	public void setCustomAtr8(String customAtr8) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr8 = customAtr8;
	}

	@JSON
	@Override
	public String getCustomAtr9() {
		if (_customAtr9 == null) {
			return "";
		}
		else {
			return _customAtr9;
		}
	}

	@Override
	public void setCustomAtr9(String customAtr9) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr9 = customAtr9;
	}

	@JSON
	@Override
	public String getCustomAtr10() {
		if (_customAtr10 == null) {
			return "";
		}
		else {
			return _customAtr10;
		}
	}

	@Override
	public void setCustomAtr10(String customAtr10) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customAtr10 = customAtr10;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCreatedBy() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("createdBy"));
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ipAddress = ipAddress;
	}

	@JSON
	@Override
	public Boolean getIsActive() {
		return _isActive;
	}

	@Override
	public void setIsActive(Boolean isActive) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isActive = isActive;
	}

	@JSON
	@Override
	public Boolean getDownForSeller() {
		return _downForSeller;
	}

	@Override
	public void setDownForSeller(Boolean downForSeller) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_downForSeller = downForSeller;
	}

	@JSON
	@Override
	public Boolean getDownForBuyer() {
		return _downForBuyer;
	}

	@Override
	public void setDownForBuyer(Boolean downForBuyer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_downForBuyer = downForBuyer;
	}

	@JSON
	@Override
	public Boolean getDownForMaintenance() {
		return _downForMaintenance;
	}

	@Override
	public void setDownForMaintenance(Boolean downForMaintenance) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_downForMaintenance = downForMaintenance;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Category.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Category.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Category toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Category>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CategoryImpl categoryImpl = new CategoryImpl();

		categoryImpl.setUuid(getUuid());
		categoryImpl.setCategoryId(getCategoryId());
		categoryImpl.setParentCategoryId(getParentCategoryId());
		categoryImpl.setAssetCategoryId(getAssetCategoryId());
		categoryImpl.setGroupId(getGroupId());
		categoryImpl.setCategoryName(getCategoryName());
		categoryImpl.setCategoryCode(getCategoryCode());
		categoryImpl.setCategoryDescription(getCategoryDescription());
		categoryImpl.setCategoryType(getCategoryType());
		categoryImpl.setAssignManager(getAssignManager());
		categoryImpl.setAssignReviewer(getAssignReviewer());
		categoryImpl.setCategoryApprovalStatus(getCategoryApprovalStatus());
		categoryImpl.setReviewerRemarks(getReviewerRemarks());
		categoryImpl.setCategoryExpiryDate(getCategoryExpiryDate());
		categoryImpl.setCategoryInactive(getCategoryInactive());
		categoryImpl.setExternalReferenceId(getExternalReferenceId());
		categoryImpl.setCategoryImageId(getCategoryImageId());
		categoryImpl.setCategoryImageURL(getCategoryImageURL());
		categoryImpl.setManagerRemarks(getManagerRemarks());
		categoryImpl.setTreePath(getTreePath());
		categoryImpl.setTermsCondition(getTermsCondition());
		categoryImpl.setHasChild(getHasChild());
		categoryImpl.setCustomAtr1(getCustomAtr1());
		categoryImpl.setCustomAtr2(getCustomAtr2());
		categoryImpl.setCustomAtr3(getCustomAtr3());
		categoryImpl.setCustomAtr4(getCustomAtr4());
		categoryImpl.setCustomAtr5(getCustomAtr5());
		categoryImpl.setCustomAtr6(getCustomAtr6());
		categoryImpl.setCustomAtr7(getCustomAtr7());
		categoryImpl.setCustomAtr8(getCustomAtr8());
		categoryImpl.setCustomAtr9(getCustomAtr9());
		categoryImpl.setCustomAtr10(getCustomAtr10());
		categoryImpl.setCreatedBy(getCreatedBy());
		categoryImpl.setModifiedBy(getModifiedBy());
		categoryImpl.setIpAddress(getIpAddress());
		categoryImpl.setIsActive(getIsActive());
		categoryImpl.setDownForSeller(getDownForSeller());
		categoryImpl.setDownForBuyer(getDownForBuyer());
		categoryImpl.setDownForMaintenance(getDownForMaintenance());
		categoryImpl.setCompanyId(getCompanyId());
		categoryImpl.setUserId(getUserId());
		categoryImpl.setUserName(getUserName());
		categoryImpl.setCreateDate(getCreateDate());
		categoryImpl.setModifiedDate(getModifiedDate());
		categoryImpl.setStatus(getStatus());
		categoryImpl.setStatusByUserId(getStatusByUserId());
		categoryImpl.setStatusByUserName(getStatusByUserName());
		categoryImpl.setStatusDate(getStatusDate());

		categoryImpl.resetOriginalValues();

		return categoryImpl;
	}

	@Override
	public Category cloneWithOriginalValues() {
		CategoryImpl categoryImpl = new CategoryImpl();

		categoryImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		categoryImpl.setCategoryId(
			this.<Long>getColumnOriginalValue("categoryId"));
		categoryImpl.setParentCategoryId(
			this.<Long>getColumnOriginalValue("parentCategoryId"));
		categoryImpl.setAssetCategoryId(
			this.<Long>getColumnOriginalValue("assetCategoryId"));
		categoryImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		categoryImpl.setCategoryName(
			this.<String>getColumnOriginalValue("categoryName"));
		categoryImpl.setCategoryCode(
			this.<String>getColumnOriginalValue("categoryCode"));
		categoryImpl.setCategoryDescription(
			this.<String>getColumnOriginalValue("categoryDescription"));
		categoryImpl.setCategoryType(
			this.<String>getColumnOriginalValue("categoryType"));
		categoryImpl.setAssignManager(
			this.<Long>getColumnOriginalValue("assignManager"));
		categoryImpl.setAssignReviewer(
			this.<Long>getColumnOriginalValue("assignReviewer"));
		categoryImpl.setCategoryApprovalStatus(
			this.<String>getColumnOriginalValue("categoryApprovalStatus"));
		categoryImpl.setReviewerRemarks(
			this.<String>getColumnOriginalValue("reviewerRemarks"));
		categoryImpl.setCategoryExpiryDate(
			this.<Date>getColumnOriginalValue("categoryExpiryDate"));
		categoryImpl.setCategoryInactive(
			this.<Boolean>getColumnOriginalValue("categoryInactive"));
		categoryImpl.setExternalReferenceId(
			this.<String>getColumnOriginalValue("externalReferenceId"));
		categoryImpl.setCategoryImageId(
			this.<Long>getColumnOriginalValue("categoryImageId"));
		categoryImpl.setCategoryImageURL(
			this.<String>getColumnOriginalValue("categoryImageURL"));
		categoryImpl.setManagerRemarks(
			this.<String>getColumnOriginalValue("managerRemarks"));
		categoryImpl.setTreePath(
			this.<String>getColumnOriginalValue("treePath"));
		categoryImpl.setTermsCondition(
			this.<String>getColumnOriginalValue("termsCondition"));
		categoryImpl.setHasChild(
			this.<Boolean>getColumnOriginalValue("hasChild"));
		categoryImpl.setCustomAtr1(
			this.<String>getColumnOriginalValue("customAtr1"));
		categoryImpl.setCustomAtr2(
			this.<String>getColumnOriginalValue("customAtr2"));
		categoryImpl.setCustomAtr3(
			this.<String>getColumnOriginalValue("customAtr3"));
		categoryImpl.setCustomAtr4(
			this.<String>getColumnOriginalValue("customAtr4"));
		categoryImpl.setCustomAtr5(
			this.<String>getColumnOriginalValue("customAtr5"));
		categoryImpl.setCustomAtr6(
			this.<String>getColumnOriginalValue("customAtr6"));
		categoryImpl.setCustomAtr7(
			this.<String>getColumnOriginalValue("customAtr7"));
		categoryImpl.setCustomAtr8(
			this.<String>getColumnOriginalValue("customAtr8"));
		categoryImpl.setCustomAtr9(
			this.<String>getColumnOriginalValue("customAtr9"));
		categoryImpl.setCustomAtr10(
			this.<String>getColumnOriginalValue("customAtr10"));
		categoryImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		categoryImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		categoryImpl.setIpAddress(
			this.<String>getColumnOriginalValue("ipAddress"));
		categoryImpl.setIsActive(
			this.<Boolean>getColumnOriginalValue("isActive"));
		categoryImpl.setDownForSeller(
			this.<Boolean>getColumnOriginalValue("downForSeller"));
		categoryImpl.setDownForBuyer(
			this.<Boolean>getColumnOriginalValue("downForBuyer"));
		categoryImpl.setDownForMaintenance(
			this.<Boolean>getColumnOriginalValue("downForMaintenance"));
		categoryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		categoryImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		categoryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		categoryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		categoryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		categoryImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		categoryImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		categoryImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		categoryImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return categoryImpl;
	}

	@Override
	public int compareTo(Category category) {
		long primaryKey = category.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Category)) {
			return false;
		}

		Category category = (Category)object;

		long primaryKey = category.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Category> toCacheModel() {
		CategoryCacheModel categoryCacheModel = new CategoryCacheModel();

		categoryCacheModel.uuid = getUuid();

		String uuid = categoryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			categoryCacheModel.uuid = null;
		}

		categoryCacheModel.categoryId = getCategoryId();

		categoryCacheModel.parentCategoryId = getParentCategoryId();

		categoryCacheModel.assetCategoryId = getAssetCategoryId();

		categoryCacheModel.groupId = getGroupId();

		categoryCacheModel.categoryName = getCategoryName();

		String categoryName = categoryCacheModel.categoryName;

		if ((categoryName != null) && (categoryName.length() == 0)) {
			categoryCacheModel.categoryName = null;
		}

		categoryCacheModel.categoryCode = getCategoryCode();

		String categoryCode = categoryCacheModel.categoryCode;

		if ((categoryCode != null) && (categoryCode.length() == 0)) {
			categoryCacheModel.categoryCode = null;
		}

		categoryCacheModel.categoryDescription = getCategoryDescription();

		String categoryDescription = categoryCacheModel.categoryDescription;

		if ((categoryDescription != null) &&
			(categoryDescription.length() == 0)) {

			categoryCacheModel.categoryDescription = null;
		}

		categoryCacheModel.categoryType = getCategoryType();

		String categoryType = categoryCacheModel.categoryType;

		if ((categoryType != null) && (categoryType.length() == 0)) {
			categoryCacheModel.categoryType = null;
		}

		categoryCacheModel.assignManager = getAssignManager();

		categoryCacheModel.assignReviewer = getAssignReviewer();

		categoryCacheModel.categoryApprovalStatus = getCategoryApprovalStatus();

		String categoryApprovalStatus =
			categoryCacheModel.categoryApprovalStatus;

		if ((categoryApprovalStatus != null) &&
			(categoryApprovalStatus.length() == 0)) {

			categoryCacheModel.categoryApprovalStatus = null;
		}

		categoryCacheModel.reviewerRemarks = getReviewerRemarks();

		String reviewerRemarks = categoryCacheModel.reviewerRemarks;

		if ((reviewerRemarks != null) && (reviewerRemarks.length() == 0)) {
			categoryCacheModel.reviewerRemarks = null;
		}

		Date categoryExpiryDate = getCategoryExpiryDate();

		if (categoryExpiryDate != null) {
			categoryCacheModel.categoryExpiryDate =
				categoryExpiryDate.getTime();
		}
		else {
			categoryCacheModel.categoryExpiryDate = Long.MIN_VALUE;
		}

		Boolean categoryInactive = getCategoryInactive();

		if (categoryInactive != null) {
			categoryCacheModel.categoryInactive = categoryInactive;
		}

		categoryCacheModel.externalReferenceId = getExternalReferenceId();

		String externalReferenceId = categoryCacheModel.externalReferenceId;

		if ((externalReferenceId != null) &&
			(externalReferenceId.length() == 0)) {

			categoryCacheModel.externalReferenceId = null;
		}

		categoryCacheModel.categoryImageId = getCategoryImageId();

		categoryCacheModel.categoryImageURL = getCategoryImageURL();

		String categoryImageURL = categoryCacheModel.categoryImageURL;

		if ((categoryImageURL != null) && (categoryImageURL.length() == 0)) {
			categoryCacheModel.categoryImageURL = null;
		}

		categoryCacheModel.managerRemarks = getManagerRemarks();

		String managerRemarks = categoryCacheModel.managerRemarks;

		if ((managerRemarks != null) && (managerRemarks.length() == 0)) {
			categoryCacheModel.managerRemarks = null;
		}

		categoryCacheModel.treePath = getTreePath();

		String treePath = categoryCacheModel.treePath;

		if ((treePath != null) && (treePath.length() == 0)) {
			categoryCacheModel.treePath = null;
		}

		categoryCacheModel.termsCondition = getTermsCondition();

		String termsCondition = categoryCacheModel.termsCondition;

		if ((termsCondition != null) && (termsCondition.length() == 0)) {
			categoryCacheModel.termsCondition = null;
		}

		Boolean hasChild = getHasChild();

		if (hasChild != null) {
			categoryCacheModel.hasChild = hasChild;
		}

		categoryCacheModel.customAtr1 = getCustomAtr1();

		String customAtr1 = categoryCacheModel.customAtr1;

		if ((customAtr1 != null) && (customAtr1.length() == 0)) {
			categoryCacheModel.customAtr1 = null;
		}

		categoryCacheModel.customAtr2 = getCustomAtr2();

		String customAtr2 = categoryCacheModel.customAtr2;

		if ((customAtr2 != null) && (customAtr2.length() == 0)) {
			categoryCacheModel.customAtr2 = null;
		}

		categoryCacheModel.customAtr3 = getCustomAtr3();

		String customAtr3 = categoryCacheModel.customAtr3;

		if ((customAtr3 != null) && (customAtr3.length() == 0)) {
			categoryCacheModel.customAtr3 = null;
		}

		categoryCacheModel.customAtr4 = getCustomAtr4();

		String customAtr4 = categoryCacheModel.customAtr4;

		if ((customAtr4 != null) && (customAtr4.length() == 0)) {
			categoryCacheModel.customAtr4 = null;
		}

		categoryCacheModel.customAtr5 = getCustomAtr5();

		String customAtr5 = categoryCacheModel.customAtr5;

		if ((customAtr5 != null) && (customAtr5.length() == 0)) {
			categoryCacheModel.customAtr5 = null;
		}

		categoryCacheModel.customAtr6 = getCustomAtr6();

		String customAtr6 = categoryCacheModel.customAtr6;

		if ((customAtr6 != null) && (customAtr6.length() == 0)) {
			categoryCacheModel.customAtr6 = null;
		}

		categoryCacheModel.customAtr7 = getCustomAtr7();

		String customAtr7 = categoryCacheModel.customAtr7;

		if ((customAtr7 != null) && (customAtr7.length() == 0)) {
			categoryCacheModel.customAtr7 = null;
		}

		categoryCacheModel.customAtr8 = getCustomAtr8();

		String customAtr8 = categoryCacheModel.customAtr8;

		if ((customAtr8 != null) && (customAtr8.length() == 0)) {
			categoryCacheModel.customAtr8 = null;
		}

		categoryCacheModel.customAtr9 = getCustomAtr9();

		String customAtr9 = categoryCacheModel.customAtr9;

		if ((customAtr9 != null) && (customAtr9.length() == 0)) {
			categoryCacheModel.customAtr9 = null;
		}

		categoryCacheModel.customAtr10 = getCustomAtr10();

		String customAtr10 = categoryCacheModel.customAtr10;

		if ((customAtr10 != null) && (customAtr10.length() == 0)) {
			categoryCacheModel.customAtr10 = null;
		}

		categoryCacheModel.createdBy = getCreatedBy();

		categoryCacheModel.modifiedBy = getModifiedBy();

		categoryCacheModel.ipAddress = getIpAddress();

		String ipAddress = categoryCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			categoryCacheModel.ipAddress = null;
		}

		Boolean isActive = getIsActive();

		if (isActive != null) {
			categoryCacheModel.isActive = isActive;
		}

		Boolean downForSeller = getDownForSeller();

		if (downForSeller != null) {
			categoryCacheModel.downForSeller = downForSeller;
		}

		Boolean downForBuyer = getDownForBuyer();

		if (downForBuyer != null) {
			categoryCacheModel.downForBuyer = downForBuyer;
		}

		Boolean downForMaintenance = getDownForMaintenance();

		if (downForMaintenance != null) {
			categoryCacheModel.downForMaintenance = downForMaintenance;
		}

		categoryCacheModel.companyId = getCompanyId();

		categoryCacheModel.userId = getUserId();

		categoryCacheModel.userName = getUserName();

		String userName = categoryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			categoryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			categoryCacheModel.createDate = createDate.getTime();
		}
		else {
			categoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			categoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			categoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		categoryCacheModel.status = getStatus();

		categoryCacheModel.statusByUserId = getStatusByUserId();

		categoryCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = categoryCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			categoryCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			categoryCacheModel.statusDate = statusDate.getTime();
		}
		else {
			categoryCacheModel.statusDate = Long.MIN_VALUE;
		}

		return categoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Category, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Category, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Category, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Category)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Category>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Category.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _categoryId;
	private long _parentCategoryId;
	private long _assetCategoryId;
	private long _groupId;
	private String _categoryName;
	private String _categoryCode;
	private String _categoryDescription;
	private String _categoryType;
	private long _assignManager;
	private long _assignReviewer;
	private String _categoryApprovalStatus;
	private String _reviewerRemarks;
	private Date _categoryExpiryDate;
	private Boolean _categoryInactive;
	private String _externalReferenceId;
	private long _categoryImageId;
	private String _categoryImageURL;
	private String _managerRemarks;
	private String _treePath;
	private String _termsCondition;
	private Boolean _hasChild;
	private String _customAtr1;
	private String _customAtr2;
	private String _customAtr3;
	private String _customAtr4;
	private String _customAtr5;
	private String _customAtr6;
	private String _customAtr7;
	private String _customAtr8;
	private String _customAtr9;
	private String _customAtr10;
	private long _createdBy;
	private long _modifiedBy;
	private String _ipAddress;
	private Boolean _isActive;
	private Boolean _downForSeller;
	private Boolean _downForBuyer;
	private Boolean _downForMaintenance;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Category, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Category)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("categoryId", _categoryId);
		_columnOriginalValues.put("parentCategoryId", _parentCategoryId);
		_columnOriginalValues.put("assetCategoryId", _assetCategoryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("categoryName", _categoryName);
		_columnOriginalValues.put("categoryCode", _categoryCode);
		_columnOriginalValues.put("categoryDescription", _categoryDescription);
		_columnOriginalValues.put("categoryType", _categoryType);
		_columnOriginalValues.put("assignManager", _assignManager);
		_columnOriginalValues.put("assignReviewer", _assignReviewer);
		_columnOriginalValues.put(
			"categoryApprovalStatus", _categoryApprovalStatus);
		_columnOriginalValues.put("reviewerRemarks", _reviewerRemarks);
		_columnOriginalValues.put("categoryExpiryDate", _categoryExpiryDate);
		_columnOriginalValues.put("categoryInactive", _categoryInactive);
		_columnOriginalValues.put("externalReferenceId", _externalReferenceId);
		_columnOriginalValues.put("categoryImageId", _categoryImageId);
		_columnOriginalValues.put("categoryImageURL", _categoryImageURL);
		_columnOriginalValues.put("managerRemarks", _managerRemarks);
		_columnOriginalValues.put("treePath", _treePath);
		_columnOriginalValues.put("termsCondition", _termsCondition);
		_columnOriginalValues.put("hasChild", _hasChild);
		_columnOriginalValues.put("customAtr1", _customAtr1);
		_columnOriginalValues.put("customAtr2", _customAtr2);
		_columnOriginalValues.put("customAtr3", _customAtr3);
		_columnOriginalValues.put("customAtr4", _customAtr4);
		_columnOriginalValues.put("customAtr5", _customAtr5);
		_columnOriginalValues.put("customAtr6", _customAtr6);
		_columnOriginalValues.put("customAtr7", _customAtr7);
		_columnOriginalValues.put("customAtr8", _customAtr8);
		_columnOriginalValues.put("customAtr9", _customAtr9);
		_columnOriginalValues.put("customAtr10", _customAtr10);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("ipAddress", _ipAddress);
		_columnOriginalValues.put("isActive", _isActive);
		_columnOriginalValues.put("downForSeller", _downForSeller);
		_columnOriginalValues.put("downForBuyer", _downForBuyer);
		_columnOriginalValues.put("downForMaintenance", _downForMaintenance);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("categoryId", 2L);

		columnBitmasks.put("parentCategoryId", 4L);

		columnBitmasks.put("assetCategoryId", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("categoryName", 32L);

		columnBitmasks.put("categoryCode", 64L);

		columnBitmasks.put("categoryDescription", 128L);

		columnBitmasks.put("categoryType", 256L);

		columnBitmasks.put("assignManager", 512L);

		columnBitmasks.put("assignReviewer", 1024L);

		columnBitmasks.put("categoryApprovalStatus", 2048L);

		columnBitmasks.put("reviewerRemarks", 4096L);

		columnBitmasks.put("categoryExpiryDate", 8192L);

		columnBitmasks.put("categoryInactive", 16384L);

		columnBitmasks.put("externalReferenceId", 32768L);

		columnBitmasks.put("categoryImageId", 65536L);

		columnBitmasks.put("categoryImageURL", 131072L);

		columnBitmasks.put("managerRemarks", 262144L);

		columnBitmasks.put("treePath", 524288L);

		columnBitmasks.put("termsCondition", 1048576L);

		columnBitmasks.put("hasChild", 2097152L);

		columnBitmasks.put("customAtr1", 4194304L);

		columnBitmasks.put("customAtr2", 8388608L);

		columnBitmasks.put("customAtr3", 16777216L);

		columnBitmasks.put("customAtr4", 33554432L);

		columnBitmasks.put("customAtr5", 67108864L);

		columnBitmasks.put("customAtr6", 134217728L);

		columnBitmasks.put("customAtr7", 268435456L);

		columnBitmasks.put("customAtr8", 536870912L);

		columnBitmasks.put("customAtr9", 1073741824L);

		columnBitmasks.put("customAtr10", 2147483648L);

		columnBitmasks.put("createdBy", 4294967296L);

		columnBitmasks.put("modifiedBy", 8589934592L);

		columnBitmasks.put("ipAddress", 17179869184L);

		columnBitmasks.put("isActive", 34359738368L);

		columnBitmasks.put("downForSeller", 68719476736L);

		columnBitmasks.put("downForBuyer", 137438953472L);

		columnBitmasks.put("downForMaintenance", 274877906944L);

		columnBitmasks.put("companyId", 549755813888L);

		columnBitmasks.put("userId", 1099511627776L);

		columnBitmasks.put("userName", 2199023255552L);

		columnBitmasks.put("createDate", 4398046511104L);

		columnBitmasks.put("modifiedDate", 8796093022208L);

		columnBitmasks.put("status", 17592186044416L);

		columnBitmasks.put("statusByUserId", 35184372088832L);

		columnBitmasks.put("statusByUserName", 70368744177664L);

		columnBitmasks.put("statusDate", 140737488355328L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Category _escapedModel;

}