create table marketplace_product (
	uuid_ VARCHAR(75) null,
	draftProductId LONG not null primary key,
	groupId LONG,
	brandId LONG,
	categoryId LONG,
	productName STRING null,
	productType VARCHAR(75) null,
	shortDescription STRING null,
	longDescription STRING null,
	modelNumber VARCHAR(75) null,
	productStatus VARCHAR(75) null,
	stepNumber LONG,
	productMappingId VARCHAR(30) null,
	taxCategoryId LONG,
	cpDefinitionId LONG,
	vendorId VARCHAR(75) null,
	vendorName VARCHAR(75) null,
	organizationId VARCHAR(75) null,
	organizationName VARCHAR(75) null,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createdBy LONG,
	modifiedBy LONG,
	createDate DATE null,
	modifiedDate DATE null,
	ipAddress VARCHAR(75) null
);