/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.specification.master.model.impl;

import com.marketplace.specification.master.model.Specification;
import com.marketplace.specification.master.service.SpecificationLocalServiceUtil;

/**
 * The extended model base implementation for the Specification service. Represents a row in the &quot;marketplace_specification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SpecificationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SpecificationImpl
 * @see Specification
 * @generated
 */
public abstract class SpecificationBaseImpl
	extends SpecificationModelImpl implements Specification {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a specification model instance should use the <code>Specification</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SpecificationLocalServiceUtil.addSpecification(this);
		}
		else {
			SpecificationLocalServiceUtil.updateSpecification(this);
		}
	}

}