/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marketplace.brand.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Brand service. Represents a row in the &quot;marketplace_brand&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.marketplace.brand.model.impl.BrandModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.marketplace.brand.model.impl.BrandImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Brand
 * @generated
 */
@ProviderType
public interface BrandModel
	extends BaseModel<Brand>, GroupedModel, ShardedModel, StagedAuditedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a brand model instance should use the {@link Brand} interface instead.
	 */

	/**
	 * Returns the primary key of this brand.
	 *
	 * @return the primary key of this brand
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this brand.
	 *
	 * @param primaryKey the primary key of this brand
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this brand.
	 *
	 * @return the uuid of this brand
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this brand.
	 *
	 * @param uuid the uuid of this brand
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the brand ID of this brand.
	 *
	 * @return the brand ID of this brand
	 */
	public long getBrandId();

	/**
	 * Sets the brand ID of this brand.
	 *
	 * @param brandId the brand ID of this brand
	 */
	public void setBrandId(long brandId);

	/**
	 * Returns the group ID of this brand.
	 *
	 * @return the group ID of this brand
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this brand.
	 *
	 * @param groupId the group ID of this brand
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the asset category ID of this brand.
	 *
	 * @return the asset category ID of this brand
	 */
	public long getAssetCategoryId();

	/**
	 * Sets the asset category ID of this brand.
	 *
	 * @param assetCategoryId the asset category ID of this brand
	 */
	public void setAssetCategoryId(long assetCategoryId);

	/**
	 * Returns the brand code of this brand.
	 *
	 * @return the brand code of this brand
	 */
	@AutoEscape
	public String getBrandCode();

	/**
	 * Sets the brand code of this brand.
	 *
	 * @param brandCode the brand code of this brand
	 */
	public void setBrandCode(String brandCode);

	/**
	 * Returns the brand name of this brand.
	 *
	 * @return the brand name of this brand
	 */
	@AutoEscape
	public String getBrandName();

	/**
	 * Sets the brand name of this brand.
	 *
	 * @param brandName the brand name of this brand
	 */
	public void setBrandName(String brandName);

	/**
	 * Returns the brand description of this brand.
	 *
	 * @return the brand description of this brand
	 */
	@AutoEscape
	public String getBrandDescription();

	/**
	 * Sets the brand description of this brand.
	 *
	 * @param brandDescription the brand description of this brand
	 */
	public void setBrandDescription(String brandDescription);

	/**
	 * Returns the brand owner of this brand.
	 *
	 * @return the brand owner of this brand
	 */
	@AutoEscape
	public String getBrandOwner();

	/**
	 * Sets the brand owner of this brand.
	 *
	 * @param brandOwner the brand owner of this brand
	 */
	public void setBrandOwner(String brandOwner);

	/**
	 * Returns the brand reviewer of this brand.
	 *
	 * @return the brand reviewer of this brand
	 */
	public long getBrandReviewer();

	/**
	 * Sets the brand reviewer of this brand.
	 *
	 * @param brandReviewer the brand reviewer of this brand
	 */
	public void setBrandReviewer(long brandReviewer);

	/**
	 * Returns the brand type of this brand.
	 *
	 * @return the brand type of this brand
	 */
	@AutoEscape
	public String getBrandType();

	/**
	 * Sets the brand type of this brand.
	 *
	 * @param brandType the brand type of this brand
	 */
	public void setBrandType(String brandType);

	/**
	 * Returns the external reference ID of this brand.
	 *
	 * @return the external reference ID of this brand
	 */
	@AutoEscape
	public String getExternalReferenceId();

	/**
	 * Sets the external reference ID of this brand.
	 *
	 * @param externalReferenceId the external reference ID of this brand
	 */
	public void setExternalReferenceId(String externalReferenceId);

	/**
	 * Returns the brand approval status of this brand.
	 *
	 * @return the brand approval status of this brand
	 */
	@AutoEscape
	public String getBrandApprovalStatus();

	/**
	 * Sets the brand approval status of this brand.
	 *
	 * @param brandApprovalStatus the brand approval status of this brand
	 */
	public void setBrandApprovalStatus(String brandApprovalStatus);

	/**
	 * Returns the reviewer remarks of this brand.
	 *
	 * @return the reviewer remarks of this brand
	 */
	@AutoEscape
	public String getReviewerRemarks();

	/**
	 * Sets the reviewer remarks of this brand.
	 *
	 * @param reviewerRemarks the reviewer remarks of this brand
	 */
	public void setReviewerRemarks(String reviewerRemarks);

	/**
	 * Returns the brand inactive of this brand.
	 *
	 * @return the brand inactive of this brand
	 */
	public Boolean getBrandInactive();

	/**
	 * Sets the brand inactive of this brand.
	 *
	 * @param brandInactive the brand inactive of this brand
	 */
	public void setBrandInactive(Boolean brandInactive);

	/**
	 * Returns the brand image upload of this brand.
	 *
	 * @return the brand image upload of this brand
	 */
	public long getBrandImageUpload();

	/**
	 * Sets the brand image upload of this brand.
	 *
	 * @param brandImageUpload the brand image upload of this brand
	 */
	public void setBrandImageUpload(long brandImageUpload);

	/**
	 * Returns the brand image url of this brand.
	 *
	 * @return the brand image url of this brand
	 */
	@AutoEscape
	public String getBrandImageURL();

	/**
	 * Sets the brand image url of this brand.
	 *
	 * @param brandImageURL the brand image url of this brand
	 */
	public void setBrandImageURL(String brandImageURL);

	/**
	 * Returns the manager remarks of this brand.
	 *
	 * @return the manager remarks of this brand
	 */
	@AutoEscape
	public String getManagerRemarks();

	/**
	 * Sets the manager remarks of this brand.
	 *
	 * @param managerRemarks the manager remarks of this brand
	 */
	public void setManagerRemarks(String managerRemarks);

	/**
	 * Returns the custom atr1 of this brand.
	 *
	 * @return the custom atr1 of this brand
	 */
	@AutoEscape
	public String getCustomAtr1();

	/**
	 * Sets the custom atr1 of this brand.
	 *
	 * @param customAtr1 the custom atr1 of this brand
	 */
	public void setCustomAtr1(String customAtr1);

	/**
	 * Returns the custom atr2 of this brand.
	 *
	 * @return the custom atr2 of this brand
	 */
	@AutoEscape
	public String getCustomAtr2();

	/**
	 * Sets the custom atr2 of this brand.
	 *
	 * @param customAtr2 the custom atr2 of this brand
	 */
	public void setCustomAtr2(String customAtr2);

	/**
	 * Returns the custom atr3 of this brand.
	 *
	 * @return the custom atr3 of this brand
	 */
	@AutoEscape
	public String getCustomAtr3();

	/**
	 * Sets the custom atr3 of this brand.
	 *
	 * @param customAtr3 the custom atr3 of this brand
	 */
	public void setCustomAtr3(String customAtr3);

	/**
	 * Returns the custom atr4 of this brand.
	 *
	 * @return the custom atr4 of this brand
	 */
	@AutoEscape
	public String getCustomAtr4();

	/**
	 * Sets the custom atr4 of this brand.
	 *
	 * @param customAtr4 the custom atr4 of this brand
	 */
	public void setCustomAtr4(String customAtr4);

	/**
	 * Returns the custom atr5 of this brand.
	 *
	 * @return the custom atr5 of this brand
	 */
	@AutoEscape
	public String getCustomAtr5();

	/**
	 * Sets the custom atr5 of this brand.
	 *
	 * @param customAtr5 the custom atr5 of this brand
	 */
	public void setCustomAtr5(String customAtr5);

	/**
	 * Returns the custom atr6 of this brand.
	 *
	 * @return the custom atr6 of this brand
	 */
	@AutoEscape
	public String getCustomAtr6();

	/**
	 * Sets the custom atr6 of this brand.
	 *
	 * @param customAtr6 the custom atr6 of this brand
	 */
	public void setCustomAtr6(String customAtr6);

	/**
	 * Returns the custom atr7 of this brand.
	 *
	 * @return the custom atr7 of this brand
	 */
	@AutoEscape
	public String getCustomAtr7();

	/**
	 * Sets the custom atr7 of this brand.
	 *
	 * @param customAtr7 the custom atr7 of this brand
	 */
	public void setCustomAtr7(String customAtr7);

	/**
	 * Returns the custom atr8 of this brand.
	 *
	 * @return the custom atr8 of this brand
	 */
	@AutoEscape
	public String getCustomAtr8();

	/**
	 * Sets the custom atr8 of this brand.
	 *
	 * @param customAtr8 the custom atr8 of this brand
	 */
	public void setCustomAtr8(String customAtr8);

	/**
	 * Returns the custom atr9 of this brand.
	 *
	 * @return the custom atr9 of this brand
	 */
	@AutoEscape
	public String getCustomAtr9();

	/**
	 * Sets the custom atr9 of this brand.
	 *
	 * @param customAtr9 the custom atr9 of this brand
	 */
	public void setCustomAtr9(String customAtr9);

	/**
	 * Returns the custom atr10 of this brand.
	 *
	 * @return the custom atr10 of this brand
	 */
	@AutoEscape
	public String getCustomAtr10();

	/**
	 * Sets the custom atr10 of this brand.
	 *
	 * @param customAtr10 the custom atr10 of this brand
	 */
	public void setCustomAtr10(String customAtr10);

	/**
	 * Returns the company ID of this brand.
	 *
	 * @return the company ID of this brand
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this brand.
	 *
	 * @param companyId the company ID of this brand
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this brand.
	 *
	 * @return the create date of this brand
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this brand.
	 *
	 * @param createDate the create date of this brand
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this brand.
	 *
	 * @return the modified date of this brand
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this brand.
	 *
	 * @param modifiedDate the modified date of this brand
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this brand.
	 *
	 * @return the created by of this brand
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this brand.
	 *
	 * @param createdBy the created by of this brand
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this brand.
	 *
	 * @return the modified by of this brand
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this brand.
	 *
	 * @param modifiedBy the modified by of this brand
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the ip address of this brand.
	 *
	 * @return the ip address of this brand
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this brand.
	 *
	 * @param ipAddress the ip address of this brand
	 */
	public void setIpAddress(String ipAddress);

	/**
	 * Returns the is active of this brand.
	 *
	 * @return the is active of this brand
	 */
	public Boolean getIsActive();

	/**
	 * Sets the is active of this brand.
	 *
	 * @param isActive the is active of this brand
	 */
	public void setIsActive(Boolean isActive);

	/**
	 * Returns the down for seller of this brand.
	 *
	 * @return the down for seller of this brand
	 */
	public Boolean getDownForSeller();

	/**
	 * Sets the down for seller of this brand.
	 *
	 * @param downForSeller the down for seller of this brand
	 */
	public void setDownForSeller(Boolean downForSeller);

	/**
	 * Returns the down for buyer of this brand.
	 *
	 * @return the down for buyer of this brand
	 */
	public Boolean getDownForBuyer();

	/**
	 * Sets the down for buyer of this brand.
	 *
	 * @param downForBuyer the down for buyer of this brand
	 */
	public void setDownForBuyer(Boolean downForBuyer);

	/**
	 * Returns the down for maintenance of this brand.
	 *
	 * @return the down for maintenance of this brand
	 */
	public Boolean getDownForMaintenance();

	/**
	 * Sets the down for maintenance of this brand.
	 *
	 * @param downForMaintenance the down for maintenance of this brand
	 */
	public void setDownForMaintenance(Boolean downForMaintenance);

	/**
	 * Returns the user ID of this brand.
	 *
	 * @return the user ID of this brand
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this brand.
	 *
	 * @param userId the user ID of this brand
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this brand.
	 *
	 * @return the user uuid of this brand
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this brand.
	 *
	 * @param userUuid the user uuid of this brand
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this brand.
	 *
	 * @return the user name of this brand
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this brand.
	 *
	 * @param userName the user name of this brand
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the status of this brand.
	 *
	 * @return the status of this brand
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this brand.
	 *
	 * @param status the status of this brand
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this brand.
	 *
	 * @return the status by user ID of this brand
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this brand.
	 *
	 * @param statusByUserId the status by user ID of this brand
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this brand.
	 *
	 * @return the status by user uuid of this brand
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this brand.
	 *
	 * @param statusByUserUuid the status by user uuid of this brand
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this brand.
	 *
	 * @return the status by user name of this brand
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this brand.
	 *
	 * @param statusByUserName the status by user name of this brand
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this brand.
	 *
	 * @return the status date of this brand
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this brand.
	 *
	 * @param statusDate the status date of this brand
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this brand is approved.
	 *
	 * @return <code>true</code> if this brand is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this brand is denied.
	 *
	 * @return <code>true</code> if this brand is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this brand is a draft.
	 *
	 * @return <code>true</code> if this brand is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this brand is expired.
	 *
	 * @return <code>true</code> if this brand is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this brand is inactive.
	 *
	 * @return <code>true</code> if this brand is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this brand is incomplete.
	 *
	 * @return <code>true</code> if this brand is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this brand is pending.
	 *
	 * @return <code>true</code> if this brand is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this brand is scheduled.
	 *
	 * @return <code>true</code> if this brand is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public Brand cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}